// Code generated by github.com/observiq/stix-go/cmd/codegen-enums. DO NOT EDIT.
// Source: scripts/dump_matcher_enums.py from cti-pattern-matcher stix2matcher/enums.py.

package matcher

var TYPES_V21 = []string{
	"attack-pattern",
	"bundle",
	"campaign",
	"course-of-action",
	"extension-definition",
	"grouping",
	"identity",
	"incident",
	"indicator",
	"infrastructure",
	"intrusion-set",
	"language-content",
	"location",
	"malware",
	"malware-analysis",
	"marking-definition",
	"note",
	"observed-data",
	"opinion",
	"relationship",
	"report",
	"threat-actor",
	"tool",
	"sighting",
	"vulnerability",
}
