# This configuration is managed by Bindplane.
# Configuration: publishsublish:4
receivers:
    gcsevent/s-01KJT1ARE9MJ81MGRAH5AFHTJD:
        bucket_name_filter: ""
        dedup_ttl: 5m0s
        max_extension: 1h0m0s
        max_log_size: 1048576
        max_logs_emitted: 1000
        object_key_filter: ""
        poll_interval: 1s
        project_id: iris-dev-351502
        subscription_id: gcs-event-topic-sub
        workers: 5
    hostmetrics/_agent_health_metrics:
        collection_interval: 1m0s
        scrapers:
            process:
                include:
                    match_type: regexp
                    names:
                        - ^observiq-otel-collector(.exe)?$
                metrics:
                    process.context_switches:
                        enabled: false
                    process.cpu.time:
                        enabled: false
                    process.cpu.utilization:
                        enabled: true
                    process.disk.io:
                        enabled: false
                    process.disk.operations:
                        enabled: false
                    process.handles:
                        enabled: false
                    process.memory.usage:
                        enabled: false
                    process.memory.utilization:
                        enabled: true
                    process.memory.virtual:
                        enabled: false
                    process.open_file_descriptors:
                        enabled: false
                    process.paging.faults:
                        enabled: false
                    process.signals_pending:
                        enabled: false
                    process.threads:
                        enabled: false
                mute_process_exe_error: true
                mute_process_io_error: false
                mute_process_name_error: true
                mute_process_user_error: false
processors:
    metricstransform/_agent_health_metrics:
        transforms:
            - action: update
              include: process.cpu.utilization
              match_type: strict
              operations:
                - action: aggregate_labels
                  aggregation_type: sum
                  label_set: []
            - action: update
              include: (.*)$$
              match_type: regexp
              new_name: agent_health_metrics_$$1
    snapshotprocessor: null
    snapshotprocessor/_d0_null-0: null
    snapshotprocessor/_p0_c-01KJT4VNZQ67ZSRTFBMNK01E8H: null
    snapshotprocessor/_s0_source0_01KJT1ARE9MJ81MGRAH5AFHTJD: null
    throughputmeasurement/_d0_logs_null-0:
        bindplane_extension: bindplane
        enabled: true
        extra_labels: {}
        sampling_ratio: 1
    throughputmeasurement/_d0_metrics_null-0:
        bindplane_extension: bindplane
        enabled: true
        extra_labels: {}
        sampling_ratio: 1
    throughputmeasurement/_d1_logs_null-0:
        bindplane_extension: bindplane
        enabled: true
        extra_labels: {}
        sampling_ratio: 1
    throughputmeasurement/_d1_metrics_null-0:
        bindplane_extension: bindplane
        enabled: true
        extra_labels: {}
        sampling_ratio: 1
    throughputmeasurement/_p1_metrics_c-01KJT4VNZQ67ZSRTFBMNK01E8H__0:
        bindplane_extension: bindplane
        enabled: true
        extra_labels: {}
        sampling_ratio: 1
    throughputmeasurement/_s0_logs_source0_01KJT1ARE9MJ81MGRAH5AFHTJD:
        bindplane_extension: bindplane
        enabled: true
        extra_labels:
            destinations: '|null|'
            usage: "true"
        measure_log_raw_bytes: true
        sampling_ratio: 1
    throughputmeasurement/_s1_logs_source0_01KJT1ARE9MJ81MGRAH5AFHTJD:
        bindplane_extension: bindplane
        enabled: true
        extra_labels: {}
        sampling_ratio: 1
    transform/_agent_health_metrics:
        error_mode: ignore
        metric_statements:
            - context: datapoint
              statements:
                - set(attributes["agent"], "019cb442-3648-78f1-a2ca-e998a93084fb")
                - set(attributes["configuration"], "publishsublish")
                - delete_key(resource.attributes, "process.command")
                - delete_key(resource.attributes, "process.command_line")
                - delete_key(resource.attributes, "process.executable.name")
                - delete_key(resource.attributes, "process.executable.path")
                - delete_key(resource.attributes, "process.owner")
                - delete_key(resource.attributes, "process.parent_pid")
                - delete_key(resource.attributes, "process.pid")
    transform/null__drop-raw-copy:
        log_statements:
            - context: log
              statements:
                - delete_key(attributes, "log.record.original")
connectors:
    count/c-01KJT4VNZQ67ZSRTFBMNK01E8H: null
    forward/c-01KJT4VNZQ67ZSRTFBMNK01E8H: null
    forward/d-d-null: null
exporters:
    nop/null: null
    otlp_http/_agent_health_metrics:
        endpoint: http://127.0.0.1:3001/v1/agents/019cb442-3648-78f1-a2ca-e998a93084fb/health
        headers:
            X-Bindplane-Account-ID: 01KJBDBCB6RB4X3ETYBTTG99KF
        retry_on_failure:
            enabled: false
        sending_queue:
            enabled: false
        timeout: 10s
service:
    pipelines:
        logs/c-01KJT4VNZQ67ZSRTFBMNK01E8H:
            receivers:
                - forward/c-01KJT4VNZQ67ZSRTFBMNK01E8H
            processors:
                - snapshotprocessor/_p0_c-01KJT4VNZQ67ZSRTFBMNK01E8H
            exporters:
                - count/c-01KJT4VNZQ67ZSRTFBMNK01E8H
        logs/d-d-null:
            receivers:
                - forward/d-d-null
            processors:
                - throughputmeasurement/_d0_logs_null-0
                - snapshotprocessor/_d0_null-0
                - throughputmeasurement/_d1_logs_null-0
                - transform/null__drop-raw-copy
                - snapshotprocessor
            exporters:
                - nop/null
        logs/s-01KJT1ARE9MJ81MGRAH5AFHTJD:
            receivers:
                - gcsevent/s-01KJT1ARE9MJ81MGRAH5AFHTJD
            processors:
                - throughputmeasurement/_s0_logs_source0_01KJT1ARE9MJ81MGRAH5AFHTJD
                - snapshotprocessor/_s0_source0_01KJT1ARE9MJ81MGRAH5AFHTJD
                - throughputmeasurement/_s1_logs_source0_01KJT1ARE9MJ81MGRAH5AFHTJD
            exporters:
                - forward/c-01KJT4VNZQ67ZSRTFBMNK01E8H
                - forward/d-d-null
        metrics/_agent_health_metrics:
            receivers:
                - hostmetrics/_agent_health_metrics
            processors:
                - metricstransform/_agent_health_metrics
                - transform/_agent_health_metrics
            exporters:
                - otlp_http/_agent_health_metrics
        metrics/c-01KJT4VNZQ67ZSRTFBMNK01E8H__0:
            receivers:
                - count/c-01KJT4VNZQ67ZSRTFBMNK01E8H
            processors:
                - throughputmeasurement/_p1_metrics_c-01KJT4VNZQ67ZSRTFBMNK01E8H__0
            exporters:
                - forward/d-d-null
        metrics/d-d-null:
            receivers:
                - forward/d-d-null
            processors:
                - throughputmeasurement/_d0_metrics_null-0
                - snapshotprocessor/_d0_null-0
                - throughputmeasurement/_d1_metrics_null-0
                - snapshotprocessor
            exporters:
                - nop/null
    telemetry:
        metrics:
            readers:
                - pull:
                    exporter:
                        prometheus:
                            host: localhost
                            port: 8888
            level: normal
        resource:
            service.instance.id: 019cb442-3648-78f1-a2ca-e998a93084fb
