// genmappings walks the OCSF schema directory and emits internal/ocsf/mappings_generated.go
// with a complete set of observable field paths (artifact default) and curated overrides.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	schemaDir := flag.String("schema-dir", "", "Path to OCSF schema root (e.g. pkg/ocsf-schema)")
	outDir := flag.String("out", ".", "Directory to write mappings_generated.go (default: current dir)")
	flag.Parse()
	if *schemaDir == "" {
		log.Fatal("missing -schema-dir")
	}
	paths, err := collectAttributePaths(*schemaDir)
	if err != nil {
		log.Fatalf("collect paths: %v", err)
	}
	// Merge curated overrides so they get strong mappings; rest get artifact default
	m := make(map[string]struct{ Type, Property string })
	for _, p := range paths {
		if c, ok := curatedOverrides[p]; ok {
			m[p] = c
		} else {
			m[p] = struct{ Type, Property string }{"artifact", "extensions.ocsf.value"}
		}
	}
	// Ensure all curated paths are in the output
	for p, c := range curatedOverrides {
		if _, ok := m[p]; !ok {
			m[p] = c
		}
	}
	sorted := make([]string, 0, len(m))
	for k := range m {
		sorted = append(sorted, k)
	}
	sort.Strings(sorted)
	outPath := filepath.Join(*outDir, "mappings_generated.go")
	if err := emitGo(outPath, sorted, m); err != nil {
		log.Fatalf("emit: %v", err)
	}
	fmt.Printf("Wrote %s (%d paths)\n", outPath, len(sorted))
}

func collectAttributePaths(root string) ([]string, error) {
	seen := make(map[string]bool)
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(path, ".json") {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		var doc map[string]interface{}
		if err := json.Unmarshal(data, &doc); err != nil {
			return nil
		}
		collectAttributes(doc, "", seen)
		return nil
	})
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(seen))
	for k := range seen {
		out = append(out, k)
	}
	return out, nil
}

func collectAttributes(obj map[string]interface{}, prefix string, out map[string]bool) {
	attrs, ok := obj["attributes"].(map[string]interface{})
	if !ok {
		// Some schemas use "properties"
		attrs, ok = obj["properties"].(map[string]interface{})
	}
	if !ok {
		return
	}
	for name := range attrs {
		p := name
		if prefix != "" {
			p = prefix + "." + name
		}
		out[p] = true
		// Recurse into nested object definitions (value may have "attributes" or "properties")
		if v, ok := attrs[name].(map[string]interface{}); ok {
			collectAttributes(v, p, out)
		}
	}
}

func emitGo(path string, keys []string, m map[string]struct{ Type, Property string }) error {
	var b strings.Builder
	b.WriteString("// Code generated by github.com/observiq/stix-go/internal/ocsf/cmd/genmappings. DO NOT EDIT.\n")
	b.WriteString("// Run: go run ./internal/ocsf/cmd/genmappings -schema-dir ../../pkg/ocsf-schema -out .\n")
	b.WriteString("// Or: make generate-ocsf-mappings (after make subtree-add-ocsf)\n\n")
	b.WriteString("package ocsf\n\n")
	b.WriteString("// ocsfFieldToSTIXGenerated contains all OCSF attribute paths from the schema (artifact default)\n")
	b.WriteString("// plus curated overrides. Curated overrides in mappings.go take precedence at init.\n")
	b.WriteString("var ocsfFieldToSTIXGenerated = map[string]STIXMapping{\n")
	for _, k := range keys {
		v := m[k]
		b.WriteString(fmt.Sprintf("\t%q: {Type: %q, Property: %q},\n", k, v.Type, v.Property))
	}
	b.WriteString("}\n")
	return os.WriteFile(path, []byte(b.String()), 0644)
}

// curatedOverrides must match internal/ocsf curatedFieldOverrides so generated file has strong mappings.
var curatedOverrides = map[string]struct{ Type, Property string }{
	"file.name":            {"file", "name"},
	"file.path":            {"file", "name"},
	"file.size":            {"file", "size"},
	"file.hashes":          {"file", "hashes.MD5"},
	"file.mime_type":       {"file", "mime_type"},
	"device.name":          {"software", "name"},
	"device.hostname":      {"domain-name", "value"},
	"device.ip":            {"ipv4-addr", "value"},
	"device.mac":           {"mac-addr", "value"},
	"src_ip":               {"ipv4-addr", "value"},
	"dst_ip":               {"ipv4-addr", "value"},
	"src_endpoint.ip":      {"ipv4-addr", "value"},
	"dst_endpoint.ip":      {"ipv4-addr", "value"},
	"hostname":             {"domain-name", "value"},
	"domain":               {"domain-name", "value"},
	"url":                  {"url", "value"},
	"url.url":              {"url", "value"},
	"process.name":         {"process", "name"},
	"process.pid":          {"process", "pid"},
	"process.command_line": {"process", "command_line"},
	"process.executable":   {"process", "name"},
	"actor.user.name":      {"user-account", "account_login"},
	"actor.user.uid":       {"user-account", "user_id"},
	"actor.email":          {"email-addr", "value"},
	"user.name":            {"user-account", "user_id"},
	"user.uid":             {"user-account", "user_id"},
	"email.from":           {"email-addr", "value"},
	"email.to":             {"email-addr", "value"},
	"registry_key":         {"windows-registry-key", "key"},
	"registry_value":       {"windows-registry-key", "values.data"},
	"resource.name":        {"software", "name"},
	"geo.location":         {"location", "region"},
	"country":              {"location", "country"},
}
