// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/networkcheck component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("networkcheck")
	ScopeName = "github.com/observiq/bindplane-otel-contrib/receiver/networkcheckreceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
