// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/filter"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
	"slices"
	"time"
)

const (
	AggregationStrategySum = "sum"
	AggregationStrategyAvg = "avg"
	AggregationStrategyMin = "min"
	AggregationStrategyMax = "max"
)

// AttributePingMethod specifies the value ping.method attribute.
type AttributePingMethod int

const (
	_ AttributePingMethod = iota
	AttributePingMethodIcmp
	AttributePingMethodHTTP
)

// String returns the string representation of the AttributePingMethod.
func (av AttributePingMethod) String() string {
	switch av {
	case AttributePingMethodIcmp:
		return "icmp"
	case AttributePingMethodHTTP:
		return "http"
	}
	return ""
}

// MapAttributePingMethod is a helper map of string to AttributePingMethod attribute value.
var MapAttributePingMethod = map[string]AttributePingMethod{
	"icmp": AttributePingMethodIcmp,
	"http": AttributePingMethodHTTP,
}

var MetricsInfo = metricsInfo{
	NetworkDNSLookupDuration: metricInfo{
		Name:       "network.dns.lookup_duration",
		Attributes: []string{"dns.query"},
	},
	NetworkDNSStatus: metricInfo{
		Name:       "network.dns.status",
		Attributes: []string{"dns.query"},
	},
	NetworkHTTPClientConnectionDuration: metricInfo{
		Name:       "network.http.client_connection_duration",
		Attributes: []string{"dns.server"},
	},
	NetworkHTTPDNSLookupDuration: metricInfo{
		Name:       "network.http.dns_lookup_duration",
		Attributes: []string{"dns.server"},
	},
	NetworkHTTPDuration: metricInfo{
		Name:       "network.http.duration",
		Attributes: []string{"http.response.status_code", "dns.server"},
	},
	NetworkHTTPRequestDuration: metricInfo{
		Name:       "network.http.request_duration",
		Attributes: []string{"dns.server"},
	},
	NetworkHTTPResponseDuration: metricInfo{
		Name:       "network.http.response_duration",
		Attributes: []string{"dns.server"},
	},
	NetworkHTTPStatus: metricInfo{
		Name:       "network.http.status",
		Attributes: []string{"http.response.status_code", "dns.server"},
	},
	NetworkHTTPTLSHandshakeDuration: metricInfo{
		Name:       "network.http.tls_handshake_duration",
		Attributes: []string{"dns.server"},
	},
	NetworkPingLatencyAvg: metricInfo{
		Name:       "network.ping.latency_avg",
		Attributes: []string{"ping.method", "dns.server"},
	},
	NetworkPingLatencyMax: metricInfo{
		Name:       "network.ping.latency_max",
		Attributes: []string{"ping.method", "dns.server"},
	},
	NetworkPingLatencyMin: metricInfo{
		Name:       "network.ping.latency_min",
		Attributes: []string{"ping.method", "dns.server"},
	},
	NetworkPingPacketLoss: metricInfo{
		Name:       "network.ping.packet_loss",
		Attributes: []string{"ping.method", "dns.server"},
	},
	NetworkTracerouteHopLatency: metricInfo{
		Name:       "network.traceroute.hop.latency",
		Attributes: []string{"traceroute.hop.index", "traceroute.hop.address", "dns.server"},
	},
	NetworkTracerouteHopStatus: metricInfo{
		Name:       "network.traceroute.hop.status",
		Attributes: []string{"traceroute.hop.index", "traceroute.hop.address", "dns.server"},
	},
}

type metricsInfo struct {
	NetworkDNSLookupDuration            metricInfo
	NetworkDNSStatus                    metricInfo
	NetworkHTTPClientConnectionDuration metricInfo
	NetworkHTTPDNSLookupDuration        metricInfo
	NetworkHTTPDuration                 metricInfo
	NetworkHTTPRequestDuration          metricInfo
	NetworkHTTPResponseDuration         metricInfo
	NetworkHTTPStatus                   metricInfo
	NetworkHTTPTLSHandshakeDuration     metricInfo
	NetworkPingLatencyAvg               metricInfo
	NetworkPingLatencyMax               metricInfo
	NetworkPingLatencyMin               metricInfo
	NetworkPingPacketLoss               metricInfo
	NetworkTracerouteHopLatency         metricInfo
	NetworkTracerouteHopStatus          metricInfo
}

type metricInfo struct {
	Name       string
	Attributes []string
}

type metricNetworkDNSLookupDuration struct {
	data          pmetric.Metric                       // data buffer for generated metric.
	config        NetworkDNSLookupDurationMetricConfig // metric config provided by user.
	capacity      int                                  // max observed number of data points added to the metric.
	aggDataPoints []float64                            // slice containing number of aggregated datapoints at each index
}

// init fills network.dns.lookup_duration metric with initial data.
func (m *metricNetworkDNSLookupDuration) init() {
	m.data.SetName("network.dns.lookup_duration")
	m.data.SetDescription("Time for the DNS server to respond to a query.")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNetworkDNSLookupDuration) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, dnsQueryAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, NetworkDNSLookupDurationMetricAttributeKeyDNSQuery) {
		dp.Attributes().PutStr("dns.query", dnsQueryAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNetworkDNSLookupDuration) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNetworkDNSLookupDuration) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNetworkDNSLookupDuration(cfg NetworkDNSLookupDurationMetricConfig) metricNetworkDNSLookupDuration {
	m := metricNetworkDNSLookupDuration{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNetworkDNSStatus struct {
	data          pmetric.Metric               // data buffer for generated metric.
	config        NetworkDNSStatusMetricConfig // metric config provided by user.
	capacity      int                          // max observed number of data points added to the metric.
	aggDataPoints []int64                      // slice containing number of aggregated datapoints at each index
}

// init fills network.dns.status metric with initial data.
func (m *metricNetworkDNSStatus) init() {
	m.data.SetName("network.dns.status")
	m.data.SetDescription("1 if the DNS server responded successfully, 0 on error or timeout.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNetworkDNSStatus) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, dnsQueryAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, NetworkDNSStatusMetricAttributeKeyDNSQuery) {
		dp.Attributes().PutStr("dns.query", dnsQueryAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNetworkDNSStatus) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNetworkDNSStatus) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNetworkDNSStatus(cfg NetworkDNSStatusMetricConfig) metricNetworkDNSStatus {
	m := metricNetworkDNSStatus{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNetworkHTTPClientConnectionDuration struct {
	data          pmetric.Metric                                  // data buffer for generated metric.
	config        NetworkHTTPClientConnectionDurationMetricConfig // metric config provided by user.
	capacity      int                                             // max observed number of data points added to the metric.
	aggDataPoints []float64                                       // slice containing number of aggregated datapoints at each index
}

// init fills network.http.client_connection_duration metric with initial data.
func (m *metricNetworkHTTPClientConnectionDuration) init() {
	m.data.SetName("network.http.client_connection_duration")
	m.data.SetDescription("Time spent establishing the TCP connection.")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNetworkHTTPClientConnectionDuration) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, NetworkHTTPClientConnectionDurationMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNetworkHTTPClientConnectionDuration) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNetworkHTTPClientConnectionDuration) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNetworkHTTPClientConnectionDuration(cfg NetworkHTTPClientConnectionDurationMetricConfig) metricNetworkHTTPClientConnectionDuration {
	m := metricNetworkHTTPClientConnectionDuration{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNetworkHTTPDNSLookupDuration struct {
	data          pmetric.Metric                           // data buffer for generated metric.
	config        NetworkHTTPDNSLookupDurationMetricConfig // metric config provided by user.
	capacity      int                                      // max observed number of data points added to the metric.
	aggDataPoints []float64                                // slice containing number of aggregated datapoints at each index
}

// init fills network.http.dns_lookup_duration metric with initial data.
func (m *metricNetworkHTTPDNSLookupDuration) init() {
	m.data.SetName("network.http.dns_lookup_duration")
	m.data.SetDescription("Time spent resolving the target hostname via DNS.")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNetworkHTTPDNSLookupDuration) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, NetworkHTTPDNSLookupDurationMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNetworkHTTPDNSLookupDuration) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNetworkHTTPDNSLookupDuration) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNetworkHTTPDNSLookupDuration(cfg NetworkHTTPDNSLookupDurationMetricConfig) metricNetworkHTTPDNSLookupDuration {
	m := metricNetworkHTTPDNSLookupDuration{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNetworkHTTPDuration struct {
	data          pmetric.Metric                  // data buffer for generated metric.
	config        NetworkHTTPDurationMetricConfig // metric config provided by user.
	capacity      int                             // max observed number of data points added to the metric.
	aggDataPoints []float64                       // slice containing number of aggregated datapoints at each index
}

// init fills network.http.duration metric with initial data.
func (m *metricNetworkHTTPDuration) init() {
	m.data.SetName("network.http.duration")
	m.data.SetDescription("Total HTTP request round-trip duration.")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNetworkHTTPDuration) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, httpResponseStatusCodeAttributeValue int64, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, NetworkHTTPDurationMetricAttributeKeyHTTPResponseStatusCode) {
		dp.Attributes().PutInt("http.response.status_code", httpResponseStatusCodeAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, NetworkHTTPDurationMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNetworkHTTPDuration) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNetworkHTTPDuration) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNetworkHTTPDuration(cfg NetworkHTTPDurationMetricConfig) metricNetworkHTTPDuration {
	m := metricNetworkHTTPDuration{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNetworkHTTPRequestDuration struct {
	data          pmetric.Metric                         // data buffer for generated metric.
	config        NetworkHTTPRequestDurationMetricConfig // metric config provided by user.
	capacity      int                                    // max observed number of data points added to the metric.
	aggDataPoints []float64                              // slice containing number of aggregated datapoints at each index
}

// init fills network.http.request_duration metric with initial data.
func (m *metricNetworkHTTPRequestDuration) init() {
	m.data.SetName("network.http.request_duration")
	m.data.SetDescription("Time spent writing the HTTP request.")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNetworkHTTPRequestDuration) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, NetworkHTTPRequestDurationMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNetworkHTTPRequestDuration) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNetworkHTTPRequestDuration) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNetworkHTTPRequestDuration(cfg NetworkHTTPRequestDurationMetricConfig) metricNetworkHTTPRequestDuration {
	m := metricNetworkHTTPRequestDuration{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNetworkHTTPResponseDuration struct {
	data          pmetric.Metric                          // data buffer for generated metric.
	config        NetworkHTTPResponseDurationMetricConfig // metric config provided by user.
	capacity      int                                     // max observed number of data points added to the metric.
	aggDataPoints []float64                               // slice containing number of aggregated datapoints at each index
}

// init fills network.http.response_duration metric with initial data.
func (m *metricNetworkHTTPResponseDuration) init() {
	m.data.SetName("network.http.response_duration")
	m.data.SetDescription("Time spent reading the HTTP response.")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNetworkHTTPResponseDuration) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, NetworkHTTPResponseDurationMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNetworkHTTPResponseDuration) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNetworkHTTPResponseDuration) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNetworkHTTPResponseDuration(cfg NetworkHTTPResponseDurationMetricConfig) metricNetworkHTTPResponseDuration {
	m := metricNetworkHTTPResponseDuration{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNetworkHTTPStatus struct {
	data          pmetric.Metric                // data buffer for generated metric.
	config        NetworkHTTPStatusMetricConfig // metric config provided by user.
	capacity      int                           // max observed number of data points added to the metric.
	aggDataPoints []int64                       // slice containing number of aggregated datapoints at each index
}

// init fills network.http.status metric with initial data.
func (m *metricNetworkHTTPStatus) init() {
	m.data.SetName("network.http.status")
	m.data.SetDescription("1 if an HTTP response was received, 0 on connection error or timeout.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNetworkHTTPStatus) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, httpResponseStatusCodeAttributeValue int64, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, NetworkHTTPStatusMetricAttributeKeyHTTPResponseStatusCode) {
		dp.Attributes().PutInt("http.response.status_code", httpResponseStatusCodeAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, NetworkHTTPStatusMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNetworkHTTPStatus) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNetworkHTTPStatus) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNetworkHTTPStatus(cfg NetworkHTTPStatusMetricConfig) metricNetworkHTTPStatus {
	m := metricNetworkHTTPStatus{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNetworkHTTPTLSHandshakeDuration struct {
	data          pmetric.Metric                              // data buffer for generated metric.
	config        NetworkHTTPTLSHandshakeDurationMetricConfig // metric config provided by user.
	capacity      int                                         // max observed number of data points added to the metric.
	aggDataPoints []float64                                   // slice containing number of aggregated datapoints at each index
}

// init fills network.http.tls_handshake_duration metric with initial data.
func (m *metricNetworkHTTPTLSHandshakeDuration) init() {
	m.data.SetName("network.http.tls_handshake_duration")
	m.data.SetDescription("Time spent completing the TLS handshake. Zero for non-TLS targets.")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNetworkHTTPTLSHandshakeDuration) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, NetworkHTTPTLSHandshakeDurationMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNetworkHTTPTLSHandshakeDuration) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNetworkHTTPTLSHandshakeDuration) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNetworkHTTPTLSHandshakeDuration(cfg NetworkHTTPTLSHandshakeDurationMetricConfig) metricNetworkHTTPTLSHandshakeDuration {
	m := metricNetworkHTTPTLSHandshakeDuration{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNetworkPingLatencyAvg struct {
	data          pmetric.Metric                    // data buffer for generated metric.
	config        NetworkPingLatencyAvgMetricConfig // metric config provided by user.
	capacity      int                               // max observed number of data points added to the metric.
	aggDataPoints []float64                         // slice containing number of aggregated datapoints at each index
}

// init fills network.ping.latency_avg metric with initial data.
func (m *metricNetworkPingLatencyAvg) init() {
	m.data.SetName("network.ping.latency_avg")
	m.data.SetDescription("Average round-trip latency across the ping packet count.")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNetworkPingLatencyAvg) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, pingMethodAttributeValue string, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, NetworkPingLatencyAvgMetricAttributeKeyPingMethod) {
		dp.Attributes().PutStr("ping.method", pingMethodAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, NetworkPingLatencyAvgMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNetworkPingLatencyAvg) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNetworkPingLatencyAvg) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNetworkPingLatencyAvg(cfg NetworkPingLatencyAvgMetricConfig) metricNetworkPingLatencyAvg {
	m := metricNetworkPingLatencyAvg{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNetworkPingLatencyMax struct {
	data          pmetric.Metric                    // data buffer for generated metric.
	config        NetworkPingLatencyMaxMetricConfig // metric config provided by user.
	capacity      int                               // max observed number of data points added to the metric.
	aggDataPoints []float64                         // slice containing number of aggregated datapoints at each index
}

// init fills network.ping.latency_max metric with initial data.
func (m *metricNetworkPingLatencyMax) init() {
	m.data.SetName("network.ping.latency_max")
	m.data.SetDescription("Maximum round-trip latency across the ping packet count.")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNetworkPingLatencyMax) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, pingMethodAttributeValue string, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, NetworkPingLatencyMaxMetricAttributeKeyPingMethod) {
		dp.Attributes().PutStr("ping.method", pingMethodAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, NetworkPingLatencyMaxMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNetworkPingLatencyMax) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNetworkPingLatencyMax) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNetworkPingLatencyMax(cfg NetworkPingLatencyMaxMetricConfig) metricNetworkPingLatencyMax {
	m := metricNetworkPingLatencyMax{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNetworkPingLatencyMin struct {
	data          pmetric.Metric                    // data buffer for generated metric.
	config        NetworkPingLatencyMinMetricConfig // metric config provided by user.
	capacity      int                               // max observed number of data points added to the metric.
	aggDataPoints []float64                         // slice containing number of aggregated datapoints at each index
}

// init fills network.ping.latency_min metric with initial data.
func (m *metricNetworkPingLatencyMin) init() {
	m.data.SetName("network.ping.latency_min")
	m.data.SetDescription("Minimum round-trip latency across the ping packet count.")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNetworkPingLatencyMin) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, pingMethodAttributeValue string, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, NetworkPingLatencyMinMetricAttributeKeyPingMethod) {
		dp.Attributes().PutStr("ping.method", pingMethodAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, NetworkPingLatencyMinMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNetworkPingLatencyMin) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNetworkPingLatencyMin) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNetworkPingLatencyMin(cfg NetworkPingLatencyMinMetricConfig) metricNetworkPingLatencyMin {
	m := metricNetworkPingLatencyMin{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNetworkPingPacketLoss struct {
	data          pmetric.Metric                    // data buffer for generated metric.
	config        NetworkPingPacketLossMetricConfig // metric config provided by user.
	capacity      int                               // max observed number of data points added to the metric.
	aggDataPoints []float64                         // slice containing number of aggregated datapoints at each index
}

// init fills network.ping.packet_loss metric with initial data.
func (m *metricNetworkPingPacketLoss) init() {
	m.data.SetName("network.ping.packet_loss")
	m.data.SetDescription("Fraction of packets lost during the ping (0.0 to 1.0).")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNetworkPingPacketLoss) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, pingMethodAttributeValue string, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, NetworkPingPacketLossMetricAttributeKeyPingMethod) {
		dp.Attributes().PutStr("ping.method", pingMethodAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, NetworkPingPacketLossMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNetworkPingPacketLoss) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNetworkPingPacketLoss) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNetworkPingPacketLoss(cfg NetworkPingPacketLossMetricConfig) metricNetworkPingPacketLoss {
	m := metricNetworkPingPacketLoss{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNetworkTracerouteHopLatency struct {
	data          pmetric.Metric                          // data buffer for generated metric.
	config        NetworkTracerouteHopLatencyMetricConfig // metric config provided by user.
	capacity      int                                     // max observed number of data points added to the metric.
	aggDataPoints []float64                               // slice containing number of aggregated datapoints at each index
}

// init fills network.traceroute.hop.latency metric with initial data.
func (m *metricNetworkTracerouteHopLatency) init() {
	m.data.SetName("network.traceroute.hop.latency")
	m.data.SetDescription("Round-trip latency to a single traceroute hop.")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNetworkTracerouteHopLatency) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, tracerouteHopIndexAttributeValue int64, tracerouteHopAddressAttributeValue string, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, NetworkTracerouteHopLatencyMetricAttributeKeyTracerouteHopIndex) {
		dp.Attributes().PutInt("traceroute.hop.index", tracerouteHopIndexAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, NetworkTracerouteHopLatencyMetricAttributeKeyTracerouteHopAddress) {
		dp.Attributes().PutStr("traceroute.hop.address", tracerouteHopAddressAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, NetworkTracerouteHopLatencyMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNetworkTracerouteHopLatency) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNetworkTracerouteHopLatency) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNetworkTracerouteHopLatency(cfg NetworkTracerouteHopLatencyMetricConfig) metricNetworkTracerouteHopLatency {
	m := metricNetworkTracerouteHopLatency{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNetworkTracerouteHopStatus struct {
	data          pmetric.Metric                         // data buffer for generated metric.
	config        NetworkTracerouteHopStatusMetricConfig // metric config provided by user.
	capacity      int                                    // max observed number of data points added to the metric.
	aggDataPoints []int64                                // slice containing number of aggregated datapoints at each index
}

// init fills network.traceroute.hop.status metric with initial data.
func (m *metricNetworkTracerouteHopStatus) init() {
	m.data.SetName("network.traceroute.hop.status")
	m.data.SetDescription("1 if the traceroute hop answered within the timeout, 0 if it did not.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricNetworkTracerouteHopStatus) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, tracerouteHopIndexAttributeValue int64, tracerouteHopAddressAttributeValue string, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, NetworkTracerouteHopStatusMetricAttributeKeyTracerouteHopIndex) {
		dp.Attributes().PutInt("traceroute.hop.index", tracerouteHopIndexAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, NetworkTracerouteHopStatusMetricAttributeKeyTracerouteHopAddress) {
		dp.Attributes().PutStr("traceroute.hop.address", tracerouteHopAddressAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, NetworkTracerouteHopStatusMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNetworkTracerouteHopStatus) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNetworkTracerouteHopStatus) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNetworkTracerouteHopStatus(cfg NetworkTracerouteHopStatusMetricConfig) metricNetworkTracerouteHopStatus {
	m := metricNetworkTracerouteHopStatus{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                                    MetricsBuilderConfig // config of the metrics builder.
	startTime                                 pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                           int                  // maximum observed number of metrics per resource.
	metricsBuffer                             pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                                 component.BuildInfo  // contains version information.
	resourceAttributeIncludeFilter            map[string]filter.Filter
	resourceAttributeExcludeFilter            map[string]filter.Filter
	metricNetworkDNSLookupDuration            metricNetworkDNSLookupDuration
	metricNetworkDNSStatus                    metricNetworkDNSStatus
	metricNetworkHTTPClientConnectionDuration metricNetworkHTTPClientConnectionDuration
	metricNetworkHTTPDNSLookupDuration        metricNetworkHTTPDNSLookupDuration
	metricNetworkHTTPDuration                 metricNetworkHTTPDuration
	metricNetworkHTTPRequestDuration          metricNetworkHTTPRequestDuration
	metricNetworkHTTPResponseDuration         metricNetworkHTTPResponseDuration
	metricNetworkHTTPStatus                   metricNetworkHTTPStatus
	metricNetworkHTTPTLSHandshakeDuration     metricNetworkHTTPTLSHandshakeDuration
	metricNetworkPingLatencyAvg               metricNetworkPingLatencyAvg
	metricNetworkPingLatencyMax               metricNetworkPingLatencyMax
	metricNetworkPingLatencyMin               metricNetworkPingLatencyMin
	metricNetworkPingPacketLoss               metricNetworkPingPacketLoss
	metricNetworkTracerouteHopLatency         metricNetworkTracerouteHopLatency
	metricNetworkTracerouteHopStatus          metricNetworkTracerouteHopStatus
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                         mbc,
		startTime:                      pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                  pmetric.NewMetrics(),
		buildInfo:                      settings.BuildInfo,
		metricNetworkDNSLookupDuration: newMetricNetworkDNSLookupDuration(mbc.Metrics.NetworkDNSLookupDuration),
		metricNetworkDNSStatus:         newMetricNetworkDNSStatus(mbc.Metrics.NetworkDNSStatus),
		metricNetworkHTTPClientConnectionDuration: newMetricNetworkHTTPClientConnectionDuration(mbc.Metrics.NetworkHTTPClientConnectionDuration),
		metricNetworkHTTPDNSLookupDuration:        newMetricNetworkHTTPDNSLookupDuration(mbc.Metrics.NetworkHTTPDNSLookupDuration),
		metricNetworkHTTPDuration:                 newMetricNetworkHTTPDuration(mbc.Metrics.NetworkHTTPDuration),
		metricNetworkHTTPRequestDuration:          newMetricNetworkHTTPRequestDuration(mbc.Metrics.NetworkHTTPRequestDuration),
		metricNetworkHTTPResponseDuration:         newMetricNetworkHTTPResponseDuration(mbc.Metrics.NetworkHTTPResponseDuration),
		metricNetworkHTTPStatus:                   newMetricNetworkHTTPStatus(mbc.Metrics.NetworkHTTPStatus),
		metricNetworkHTTPTLSHandshakeDuration:     newMetricNetworkHTTPTLSHandshakeDuration(mbc.Metrics.NetworkHTTPTLSHandshakeDuration),
		metricNetworkPingLatencyAvg:               newMetricNetworkPingLatencyAvg(mbc.Metrics.NetworkPingLatencyAvg),
		metricNetworkPingLatencyMax:               newMetricNetworkPingLatencyMax(mbc.Metrics.NetworkPingLatencyMax),
		metricNetworkPingLatencyMin:               newMetricNetworkPingLatencyMin(mbc.Metrics.NetworkPingLatencyMin),
		metricNetworkPingPacketLoss:               newMetricNetworkPingPacketLoss(mbc.Metrics.NetworkPingPacketLoss),
		metricNetworkTracerouteHopLatency:         newMetricNetworkTracerouteHopLatency(mbc.Metrics.NetworkTracerouteHopLatency),
		metricNetworkTracerouteHopStatus:          newMetricNetworkTracerouteHopStatus(mbc.Metrics.NetworkTracerouteHopStatus),
		resourceAttributeIncludeFilter:            make(map[string]filter.Filter),
		resourceAttributeExcludeFilter:            make(map[string]filter.Filter),
	}
	if mbc.ResourceAttributes.TargetEndpoint.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["target.endpoint"] = filter.CreateFilter(mbc.ResourceAttributes.TargetEndpoint.MetricsInclude)
	}
	if mbc.ResourceAttributes.TargetEndpoint.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["target.endpoint"] = filter.CreateFilter(mbc.ResourceAttributes.TargetEndpoint.MetricsExclude)
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// NewResourceBuilder returns a new resource builder that should be used to build a resource associated with for the emitted metrics.
func (mb *MetricsBuilder) NewResourceBuilder() *ResourceBuilder {
	return NewResourceBuilder(mb.config.ResourceAttributes)
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricNetworkDNSLookupDuration.emit(ils.Metrics())
	mb.metricNetworkDNSStatus.emit(ils.Metrics())
	mb.metricNetworkHTTPClientConnectionDuration.emit(ils.Metrics())
	mb.metricNetworkHTTPDNSLookupDuration.emit(ils.Metrics())
	mb.metricNetworkHTTPDuration.emit(ils.Metrics())
	mb.metricNetworkHTTPRequestDuration.emit(ils.Metrics())
	mb.metricNetworkHTTPResponseDuration.emit(ils.Metrics())
	mb.metricNetworkHTTPStatus.emit(ils.Metrics())
	mb.metricNetworkHTTPTLSHandshakeDuration.emit(ils.Metrics())
	mb.metricNetworkPingLatencyAvg.emit(ils.Metrics())
	mb.metricNetworkPingLatencyMax.emit(ils.Metrics())
	mb.metricNetworkPingLatencyMin.emit(ils.Metrics())
	mb.metricNetworkPingPacketLoss.emit(ils.Metrics())
	mb.metricNetworkTracerouteHopLatency.emit(ils.Metrics())
	mb.metricNetworkTracerouteHopStatus.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}
	for attr, filter := range mb.resourceAttributeIncludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && !filter.Matches(val.AsString()) {
			return
		}
	}
	for attr, filter := range mb.resourceAttributeExcludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && filter.Matches(val.AsString()) {
			return
		}
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordNetworkDNSLookupDurationDataPoint adds a data point to network.dns.lookup_duration metric.
func (mb *MetricsBuilder) RecordNetworkDNSLookupDurationDataPoint(ts pcommon.Timestamp, val float64, dnsQueryAttributeValue string) {
	mb.metricNetworkDNSLookupDuration.recordDataPoint(mb.startTime, ts, val, dnsQueryAttributeValue)
}

// RecordNetworkDNSStatusDataPoint adds a data point to network.dns.status metric.
func (mb *MetricsBuilder) RecordNetworkDNSStatusDataPoint(ts pcommon.Timestamp, val int64, dnsQueryAttributeValue string) {
	mb.metricNetworkDNSStatus.recordDataPoint(mb.startTime, ts, val, dnsQueryAttributeValue)
}

// RecordNetworkHTTPClientConnectionDurationDataPoint adds a data point to network.http.client_connection_duration metric.
func (mb *MetricsBuilder) RecordNetworkHTTPClientConnectionDurationDataPoint(ts pcommon.Timestamp, val float64, dnsServerAttributeValue string) {
	mb.metricNetworkHTTPClientConnectionDuration.recordDataPoint(mb.startTime, ts, val, dnsServerAttributeValue)
}

// RecordNetworkHTTPDNSLookupDurationDataPoint adds a data point to network.http.dns_lookup_duration metric.
func (mb *MetricsBuilder) RecordNetworkHTTPDNSLookupDurationDataPoint(ts pcommon.Timestamp, val float64, dnsServerAttributeValue string) {
	mb.metricNetworkHTTPDNSLookupDuration.recordDataPoint(mb.startTime, ts, val, dnsServerAttributeValue)
}

// RecordNetworkHTTPDurationDataPoint adds a data point to network.http.duration metric.
func (mb *MetricsBuilder) RecordNetworkHTTPDurationDataPoint(ts pcommon.Timestamp, val float64, httpResponseStatusCodeAttributeValue int64, dnsServerAttributeValue string) {
	mb.metricNetworkHTTPDuration.recordDataPoint(mb.startTime, ts, val, httpResponseStatusCodeAttributeValue, dnsServerAttributeValue)
}

// RecordNetworkHTTPRequestDurationDataPoint adds a data point to network.http.request_duration metric.
func (mb *MetricsBuilder) RecordNetworkHTTPRequestDurationDataPoint(ts pcommon.Timestamp, val float64, dnsServerAttributeValue string) {
	mb.metricNetworkHTTPRequestDuration.recordDataPoint(mb.startTime, ts, val, dnsServerAttributeValue)
}

// RecordNetworkHTTPResponseDurationDataPoint adds a data point to network.http.response_duration metric.
func (mb *MetricsBuilder) RecordNetworkHTTPResponseDurationDataPoint(ts pcommon.Timestamp, val float64, dnsServerAttributeValue string) {
	mb.metricNetworkHTTPResponseDuration.recordDataPoint(mb.startTime, ts, val, dnsServerAttributeValue)
}

// RecordNetworkHTTPStatusDataPoint adds a data point to network.http.status metric.
func (mb *MetricsBuilder) RecordNetworkHTTPStatusDataPoint(ts pcommon.Timestamp, val int64, httpResponseStatusCodeAttributeValue int64, dnsServerAttributeValue string) {
	mb.metricNetworkHTTPStatus.recordDataPoint(mb.startTime, ts, val, httpResponseStatusCodeAttributeValue, dnsServerAttributeValue)
}

// RecordNetworkHTTPTLSHandshakeDurationDataPoint adds a data point to network.http.tls_handshake_duration metric.
func (mb *MetricsBuilder) RecordNetworkHTTPTLSHandshakeDurationDataPoint(ts pcommon.Timestamp, val float64, dnsServerAttributeValue string) {
	mb.metricNetworkHTTPTLSHandshakeDuration.recordDataPoint(mb.startTime, ts, val, dnsServerAttributeValue)
}

// RecordNetworkPingLatencyAvgDataPoint adds a data point to network.ping.latency_avg metric.
func (mb *MetricsBuilder) RecordNetworkPingLatencyAvgDataPoint(ts pcommon.Timestamp, val float64, pingMethodAttributeValue AttributePingMethod, dnsServerAttributeValue string) {
	mb.metricNetworkPingLatencyAvg.recordDataPoint(mb.startTime, ts, val, pingMethodAttributeValue.String(), dnsServerAttributeValue)
}

// RecordNetworkPingLatencyMaxDataPoint adds a data point to network.ping.latency_max metric.
func (mb *MetricsBuilder) RecordNetworkPingLatencyMaxDataPoint(ts pcommon.Timestamp, val float64, pingMethodAttributeValue AttributePingMethod, dnsServerAttributeValue string) {
	mb.metricNetworkPingLatencyMax.recordDataPoint(mb.startTime, ts, val, pingMethodAttributeValue.String(), dnsServerAttributeValue)
}

// RecordNetworkPingLatencyMinDataPoint adds a data point to network.ping.latency_min metric.
func (mb *MetricsBuilder) RecordNetworkPingLatencyMinDataPoint(ts pcommon.Timestamp, val float64, pingMethodAttributeValue AttributePingMethod, dnsServerAttributeValue string) {
	mb.metricNetworkPingLatencyMin.recordDataPoint(mb.startTime, ts, val, pingMethodAttributeValue.String(), dnsServerAttributeValue)
}

// RecordNetworkPingPacketLossDataPoint adds a data point to network.ping.packet_loss metric.
func (mb *MetricsBuilder) RecordNetworkPingPacketLossDataPoint(ts pcommon.Timestamp, val float64, pingMethodAttributeValue AttributePingMethod, dnsServerAttributeValue string) {
	mb.metricNetworkPingPacketLoss.recordDataPoint(mb.startTime, ts, val, pingMethodAttributeValue.String(), dnsServerAttributeValue)
}

// RecordNetworkTracerouteHopLatencyDataPoint adds a data point to network.traceroute.hop.latency metric.
func (mb *MetricsBuilder) RecordNetworkTracerouteHopLatencyDataPoint(ts pcommon.Timestamp, val float64, tracerouteHopIndexAttributeValue int64, tracerouteHopAddressAttributeValue string, dnsServerAttributeValue string) {
	mb.metricNetworkTracerouteHopLatency.recordDataPoint(mb.startTime, ts, val, tracerouteHopIndexAttributeValue, tracerouteHopAddressAttributeValue, dnsServerAttributeValue)
}

// RecordNetworkTracerouteHopStatusDataPoint adds a data point to network.traceroute.hop.status metric.
func (mb *MetricsBuilder) RecordNetworkTracerouteHopStatusDataPoint(ts pcommon.Timestamp, val int64, tracerouteHopIndexAttributeValue int64, tracerouteHopAddressAttributeValue string, dnsServerAttributeValue string) {
	mb.metricNetworkTracerouteHopStatus.recordDataPoint(mb.startTime, ts, val, tracerouteHopIndexAttributeValue, tracerouteHopAddressAttributeValue, dnsServerAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
