// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
	testDataSetReag
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "reaggregate_set",
			metricsSet:  testDataSetReag,
			resAttrsSet: testDataSetReag,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: testDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))
			aggMap := make(map[string]string) // contains the aggregation strategies for each metric name
			aggMap["network.dns.lookup_duration"] = mb.metricNetworkDNSLookupDuration.config.AggregationStrategy
			aggMap["network.dns.status"] = mb.metricNetworkDNSStatus.config.AggregationStrategy
			aggMap["network.http.client_connection_duration"] = mb.metricNetworkHTTPClientConnectionDuration.config.AggregationStrategy
			aggMap["network.http.dns_lookup_duration"] = mb.metricNetworkHTTPDNSLookupDuration.config.AggregationStrategy
			aggMap["network.http.duration"] = mb.metricNetworkHTTPDuration.config.AggregationStrategy
			aggMap["network.http.request_duration"] = mb.metricNetworkHTTPRequestDuration.config.AggregationStrategy
			aggMap["network.http.response_duration"] = mb.metricNetworkHTTPResponseDuration.config.AggregationStrategy
			aggMap["network.http.status"] = mb.metricNetworkHTTPStatus.config.AggregationStrategy
			aggMap["network.http.tls_handshake_duration"] = mb.metricNetworkHTTPTLSHandshakeDuration.config.AggregationStrategy
			aggMap["network.ping.latency_avg"] = mb.metricNetworkPingLatencyAvg.config.AggregationStrategy
			aggMap["network.ping.latency_max"] = mb.metricNetworkPingLatencyMax.config.AggregationStrategy
			aggMap["network.ping.latency_min"] = mb.metricNetworkPingLatencyMin.config.AggregationStrategy
			aggMap["network.ping.packet_loss"] = mb.metricNetworkPingPacketLoss.config.AggregationStrategy
			aggMap["network.traceroute.hop.latency"] = mb.metricNetworkTracerouteHopLatency.config.AggregationStrategy
			aggMap["network.traceroute.hop.status"] = mb.metricNetworkTracerouteHopStatus.config.AggregationStrategy

			expectedWarnings := 0
			if tt.metricsSet != testDataSetReag {
				assert.Equal(t, expectedWarnings, observedLogs.Len())
			}

			defaultMetricsCount := 0
			allMetricsCount := 0
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetworkDNSLookupDurationDataPoint(ts, 1, "dns.query-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNetworkDNSLookupDurationDataPoint(ts, 3, "dns.query-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetworkDNSStatusDataPoint(ts, 1, "dns.query-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNetworkDNSStatusDataPoint(ts, 3, "dns.query-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetworkHTTPClientConnectionDurationDataPoint(ts, 1, "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNetworkHTTPClientConnectionDurationDataPoint(ts, 3, "dns.server-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetworkHTTPDNSLookupDurationDataPoint(ts, 1, "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNetworkHTTPDNSLookupDurationDataPoint(ts, 3, "dns.server-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetworkHTTPDurationDataPoint(ts, 1, 25, "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNetworkHTTPDurationDataPoint(ts, 3, 26, "dns.server-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetworkHTTPRequestDurationDataPoint(ts, 1, "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNetworkHTTPRequestDurationDataPoint(ts, 3, "dns.server-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetworkHTTPResponseDurationDataPoint(ts, 1, "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNetworkHTTPResponseDurationDataPoint(ts, 3, "dns.server-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetworkHTTPStatusDataPoint(ts, 1, 25, "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNetworkHTTPStatusDataPoint(ts, 3, 26, "dns.server-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetworkHTTPTLSHandshakeDurationDataPoint(ts, 1, "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNetworkHTTPTLSHandshakeDurationDataPoint(ts, 3, "dns.server-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetworkPingLatencyAvgDataPoint(ts, 1, AttributePingMethodIcmp, "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNetworkPingLatencyAvgDataPoint(ts, 3, AttributePingMethodHTTP, "dns.server-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetworkPingLatencyMaxDataPoint(ts, 1, AttributePingMethodIcmp, "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNetworkPingLatencyMaxDataPoint(ts, 3, AttributePingMethodHTTP, "dns.server-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetworkPingLatencyMinDataPoint(ts, 1, AttributePingMethodIcmp, "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNetworkPingLatencyMinDataPoint(ts, 3, AttributePingMethodHTTP, "dns.server-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetworkPingPacketLossDataPoint(ts, 1, AttributePingMethodIcmp, "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNetworkPingPacketLossDataPoint(ts, 3, AttributePingMethodHTTP, "dns.server-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetworkTracerouteHopLatencyDataPoint(ts, 1, 20, "traceroute.hop.address-val", "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNetworkTracerouteHopLatencyDataPoint(ts, 3, 21, "traceroute.hop.address-val-2", "dns.server-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNetworkTracerouteHopStatusDataPoint(ts, 1, 20, "traceroute.hop.address-val", "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNetworkTracerouteHopStatusDataPoint(ts, 3, 21, "traceroute.hop.address-val-2", "dns.server-val-2")
			}

			rb := mb.NewResourceBuilder()
			rb.SetTargetEndpoint("target.endpoint-val")
			res := rb.Emit()
			metrics := mb.Emit(WithResource(res))
			if tt.name == "reaggregate_set" {
				assert.Empty(t, mb.metricNetworkDNSLookupDuration.aggDataPoints)
				assert.Empty(t, mb.metricNetworkDNSStatus.aggDataPoints)
				assert.Empty(t, mb.metricNetworkHTTPClientConnectionDuration.aggDataPoints)
				assert.Empty(t, mb.metricNetworkHTTPDNSLookupDuration.aggDataPoints)
				assert.Empty(t, mb.metricNetworkHTTPDuration.aggDataPoints)
				assert.Empty(t, mb.metricNetworkHTTPRequestDuration.aggDataPoints)
				assert.Empty(t, mb.metricNetworkHTTPResponseDuration.aggDataPoints)
				assert.Empty(t, mb.metricNetworkHTTPStatus.aggDataPoints)
				assert.Empty(t, mb.metricNetworkHTTPTLSHandshakeDuration.aggDataPoints)
				assert.Empty(t, mb.metricNetworkPingLatencyAvg.aggDataPoints)
				assert.Empty(t, mb.metricNetworkPingLatencyMax.aggDataPoints)
				assert.Empty(t, mb.metricNetworkPingLatencyMin.aggDataPoints)
				assert.Empty(t, mb.metricNetworkPingPacketLoss.aggDataPoints)
				assert.Empty(t, mb.metricNetworkTracerouteHopLatency.aggDataPoints)
				assert.Empty(t, mb.metricNetworkTracerouteHopStatus.aggDataPoints)
			}

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "network.dns.lookup_duration":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["network.dns.lookup_duration"], "Found a duplicate in the metrics slice: network.dns.lookup_duration")
						validatedMetrics["network.dns.lookup_duration"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Time for the DNS server to respond to a query.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						dnsQueryAttrVal, ok := dp.Attributes().Get("dns.query")
						assert.True(t, ok)
						assert.Equal(t, "dns.query-val", dnsQueryAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["network.dns.lookup_duration"], "Found a duplicate in the metrics slice: network.dns.lookup_duration")
						validatedMetrics["network.dns.lookup_duration"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Time for the DNS server to respond to a query.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["network.dns.lookup_duration"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("dns.query")
						assert.False(t, ok)
					}
				case "network.dns.status":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["network.dns.status"], "Found a duplicate in the metrics slice: network.dns.status")
						validatedMetrics["network.dns.status"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "1 if the DNS server responded successfully, 0 on error or timeout.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						dnsQueryAttrVal, ok := dp.Attributes().Get("dns.query")
						assert.True(t, ok)
						assert.Equal(t, "dns.query-val", dnsQueryAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["network.dns.status"], "Found a duplicate in the metrics slice: network.dns.status")
						validatedMetrics["network.dns.status"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "1 if the DNS server responded successfully, 0 on error or timeout.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["network.dns.status"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("dns.query")
						assert.False(t, ok)
					}
				case "network.http.client_connection_duration":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["network.http.client_connection_duration"], "Found a duplicate in the metrics slice: network.http.client_connection_duration")
						validatedMetrics["network.http.client_connection_duration"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Time spent establishing the TCP connection.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["network.http.client_connection_duration"], "Found a duplicate in the metrics slice: network.http.client_connection_duration")
						validatedMetrics["network.http.client_connection_duration"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Time spent establishing the TCP connection.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["network.http.client_connection_duration"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				case "network.http.dns_lookup_duration":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["network.http.dns_lookup_duration"], "Found a duplicate in the metrics slice: network.http.dns_lookup_duration")
						validatedMetrics["network.http.dns_lookup_duration"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Time spent resolving the target hostname via DNS.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["network.http.dns_lookup_duration"], "Found a duplicate in the metrics slice: network.http.dns_lookup_duration")
						validatedMetrics["network.http.dns_lookup_duration"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Time spent resolving the target hostname via DNS.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["network.http.dns_lookup_duration"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				case "network.http.duration":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["network.http.duration"], "Found a duplicate in the metrics slice: network.http.duration")
						validatedMetrics["network.http.duration"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Total HTTP request round-trip duration.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						httpResponseStatusCodeAttrVal, ok := dp.Attributes().Get("http.response.status_code")
						assert.True(t, ok)
						assert.EqualValues(t, 25, httpResponseStatusCodeAttrVal.Int())
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["network.http.duration"], "Found a duplicate in the metrics slice: network.http.duration")
						validatedMetrics["network.http.duration"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Total HTTP request round-trip duration.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["network.http.duration"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("http.response.status_code")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				case "network.http.request_duration":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["network.http.request_duration"], "Found a duplicate in the metrics slice: network.http.request_duration")
						validatedMetrics["network.http.request_duration"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Time spent writing the HTTP request.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["network.http.request_duration"], "Found a duplicate in the metrics slice: network.http.request_duration")
						validatedMetrics["network.http.request_duration"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Time spent writing the HTTP request.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["network.http.request_duration"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				case "network.http.response_duration":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["network.http.response_duration"], "Found a duplicate in the metrics slice: network.http.response_duration")
						validatedMetrics["network.http.response_duration"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Time spent reading the HTTP response.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["network.http.response_duration"], "Found a duplicate in the metrics slice: network.http.response_duration")
						validatedMetrics["network.http.response_duration"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Time spent reading the HTTP response.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["network.http.response_duration"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				case "network.http.status":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["network.http.status"], "Found a duplicate in the metrics slice: network.http.status")
						validatedMetrics["network.http.status"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "1 if an HTTP response was received, 0 on connection error or timeout.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						httpResponseStatusCodeAttrVal, ok := dp.Attributes().Get("http.response.status_code")
						assert.True(t, ok)
						assert.EqualValues(t, 25, httpResponseStatusCodeAttrVal.Int())
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["network.http.status"], "Found a duplicate in the metrics slice: network.http.status")
						validatedMetrics["network.http.status"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "1 if an HTTP response was received, 0 on connection error or timeout.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["network.http.status"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("http.response.status_code")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				case "network.http.tls_handshake_duration":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["network.http.tls_handshake_duration"], "Found a duplicate in the metrics slice: network.http.tls_handshake_duration")
						validatedMetrics["network.http.tls_handshake_duration"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Time spent completing the TLS handshake. Zero for non-TLS targets.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["network.http.tls_handshake_duration"], "Found a duplicate in the metrics slice: network.http.tls_handshake_duration")
						validatedMetrics["network.http.tls_handshake_duration"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Time spent completing the TLS handshake. Zero for non-TLS targets.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["network.http.tls_handshake_duration"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				case "network.ping.latency_avg":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["network.ping.latency_avg"], "Found a duplicate in the metrics slice: network.ping.latency_avg")
						validatedMetrics["network.ping.latency_avg"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Average round-trip latency across the ping packet count.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						pingMethodAttrVal, ok := dp.Attributes().Get("ping.method")
						assert.True(t, ok)
						assert.Equal(t, "icmp", pingMethodAttrVal.Str())
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["network.ping.latency_avg"], "Found a duplicate in the metrics slice: network.ping.latency_avg")
						validatedMetrics["network.ping.latency_avg"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Average round-trip latency across the ping packet count.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["network.ping.latency_avg"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("ping.method")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				case "network.ping.latency_max":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["network.ping.latency_max"], "Found a duplicate in the metrics slice: network.ping.latency_max")
						validatedMetrics["network.ping.latency_max"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Maximum round-trip latency across the ping packet count.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						pingMethodAttrVal, ok := dp.Attributes().Get("ping.method")
						assert.True(t, ok)
						assert.Equal(t, "icmp", pingMethodAttrVal.Str())
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["network.ping.latency_max"], "Found a duplicate in the metrics slice: network.ping.latency_max")
						validatedMetrics["network.ping.latency_max"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Maximum round-trip latency across the ping packet count.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["network.ping.latency_max"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("ping.method")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				case "network.ping.latency_min":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["network.ping.latency_min"], "Found a duplicate in the metrics slice: network.ping.latency_min")
						validatedMetrics["network.ping.latency_min"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Minimum round-trip latency across the ping packet count.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						pingMethodAttrVal, ok := dp.Attributes().Get("ping.method")
						assert.True(t, ok)
						assert.Equal(t, "icmp", pingMethodAttrVal.Str())
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["network.ping.latency_min"], "Found a duplicate in the metrics slice: network.ping.latency_min")
						validatedMetrics["network.ping.latency_min"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Minimum round-trip latency across the ping packet count.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["network.ping.latency_min"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("ping.method")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				case "network.ping.packet_loss":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["network.ping.packet_loss"], "Found a duplicate in the metrics slice: network.ping.packet_loss")
						validatedMetrics["network.ping.packet_loss"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Fraction of packets lost during the ping (0.0 to 1.0).", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						pingMethodAttrVal, ok := dp.Attributes().Get("ping.method")
						assert.True(t, ok)
						assert.Equal(t, "icmp", pingMethodAttrVal.Str())
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["network.ping.packet_loss"], "Found a duplicate in the metrics slice: network.ping.packet_loss")
						validatedMetrics["network.ping.packet_loss"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Fraction of packets lost during the ping (0.0 to 1.0).", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["network.ping.packet_loss"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("ping.method")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				case "network.traceroute.hop.latency":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["network.traceroute.hop.latency"], "Found a duplicate in the metrics slice: network.traceroute.hop.latency")
						validatedMetrics["network.traceroute.hop.latency"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Round-trip latency to a single traceroute hop.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						tracerouteHopIndexAttrVal, ok := dp.Attributes().Get("traceroute.hop.index")
						assert.True(t, ok)
						assert.EqualValues(t, 20, tracerouteHopIndexAttrVal.Int())
						tracerouteHopAddressAttrVal, ok := dp.Attributes().Get("traceroute.hop.address")
						assert.True(t, ok)
						assert.Equal(t, "traceroute.hop.address-val", tracerouteHopAddressAttrVal.Str())
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["network.traceroute.hop.latency"], "Found a duplicate in the metrics slice: network.traceroute.hop.latency")
						validatedMetrics["network.traceroute.hop.latency"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Round-trip latency to a single traceroute hop.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["network.traceroute.hop.latency"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("traceroute.hop.index")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("traceroute.hop.address")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				case "network.traceroute.hop.status":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["network.traceroute.hop.status"], "Found a duplicate in the metrics slice: network.traceroute.hop.status")
						validatedMetrics["network.traceroute.hop.status"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "1 if the traceroute hop answered within the timeout, 0 if it did not.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						tracerouteHopIndexAttrVal, ok := dp.Attributes().Get("traceroute.hop.index")
						assert.True(t, ok)
						assert.EqualValues(t, 20, tracerouteHopIndexAttrVal.Int())
						tracerouteHopAddressAttrVal, ok := dp.Attributes().Get("traceroute.hop.address")
						assert.True(t, ok)
						assert.Equal(t, "traceroute.hop.address-val", tracerouteHopAddressAttrVal.Str())
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["network.traceroute.hop.status"], "Found a duplicate in the metrics slice: network.traceroute.hop.status")
						validatedMetrics["network.traceroute.hop.status"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "1 if the traceroute hop answered within the timeout, 0 if it did not.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["network.traceroute.hop.status"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("traceroute.hop.index")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("traceroute.hop.address")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				}
			}
		})
	}
}
