// Code generated by mdatagen. DO NOT EDIT.

package gcspubsubeventreceiver

import (
	"go.uber.org/goleak"
	"testing"
)

func TestMain(m *testing.M) {
	setupTestEnvironment()
	goleak.VerifyTestMain(m)
}
