// Code generated by mdatagen. DO NOT EDIT.

package gcspubsubeventreceiver

import (
	"testing"

	"go.uber.org/goleak"
)

func TestMain(m *testing.M) {
	setupTestEnvironment()
	goleak.VerifyTestMain(m)
}
