package validatorcodegen

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// Generate produces Go source for package validator containing
// generatedTypeToPath and generatedSchemas.
func Generate(schemas map[string]Schema, typeToPath map[string]string) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by github.com/observiq/stix-go/cmd/codegen-validator. DO NOT EDIT.\n")
	b.WriteString("// Source: STIX 2.1 JSON schemas (cti-stix2-json-schemas/schemas).\n\n")
	b.WriteString("package validator\n\n")
	b.WriteString("import \"regexp\"\n\n")

	// TypeToPath map
	b.WriteString("var generatedTypeToPath = map[string]string{\n")
	keys := make([]string, 0, len(typeToPath))
	for k := range typeToPath {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		b.WriteString("\t")
		b.WriteString(strconv.Quote(k))
		b.WriteString(": ")
		b.WriteString(strconv.Quote(typeToPath[k]))
		b.WriteString(",\n")
	}
	b.WriteString("}\n\n")

	// Schemas map: path -> RawSchema (map[string]interface{})
	b.WriteString("var generatedSchemas = map[string]RawSchema{\n")
	schemaPaths := make([]string, 0, len(schemas))
	for p := range schemas {
		schemaPaths = append(schemaPaths, p)
	}
	sort.Strings(schemaPaths)
	for _, path := range schemaPaths {
		s := schemas[path]
		b.WriteString("\t")
		b.WriteString(strconv.Quote(path))
		b.WriteString(": ")
		// Emit as map[string]interface{} so generated code does not reference codegen package.
		emitValue(&b, map[string]interface{}(s), 1)
		b.WriteString(",\n")
	}
	b.WriteString("}\n\n")

	// Typed schemas populated at init from generatedSchemas
	b.WriteString("var generatedSchemasTyped map[string]*Schema\n\n")
	b.WriteString("func init() {\n")
	b.WriteString("\tgeneratedSchemasTyped = ConvertSchemas(generatedSchemas)\n")
	b.WriteString("}\n\n")

	// Compiled schemas (path→constraints per root type)
	if err := emitCompiledMap(&b, typeToPath, schemas); err != nil {
		return nil, err
	}

	return []byte(b.String()), nil
}

func emitValue(b *strings.Builder, v interface{}, indent int) {
	if v == nil {
		b.WriteString("nil")
		return
	}
	switch x := v.(type) {
	case map[string]interface{}:
		emitMap(b, x, indent)
	case []interface{}:
		emitSlice(b, x, indent)
	case string:
		b.WriteString(strconv.Quote(x))
	case float64:
		b.WriteString(strconv.FormatFloat(x, 'g', -1, 64))
	case bool:
		if x {
			b.WriteString("true")
		} else {
			b.WriteString("false")
		}
	default:
		b.WriteString(fmt.Sprintf("%#v", x))
	}
}

func emitMap(b *strings.Builder, m map[string]interface{}, indent int) {
	if len(m) == 0 {
		b.WriteString("map[string]interface{}{}")
		return
	}
	b.WriteString("map[string]interface{}{\n")
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	tab := strings.Repeat("\t", indent+1)
	for _, k := range keys {
		b.WriteString(tab)
		b.WriteString(strconv.Quote(k))
		b.WriteString(": ")
		emitValue(b, m[k], indent+1)
		b.WriteString(",\n")
	}
	b.WriteString(strings.Repeat("\t", indent))
	b.WriteString("}")
}

func emitSlice(b *strings.Builder, s []interface{}, indent int) {
	if len(s) == 0 {
		b.WriteString("[]interface{}{}")
		return
	}
	b.WriteString("[]interface{}{\n")
	tab := strings.Repeat("\t", indent+1)
	for _, v := range s {
		b.WriteString(tab)
		emitValue(b, v, indent+1)
		b.WriteString(",\n")
	}
	b.WriteString(strings.Repeat("\t", indent))
	b.WriteString("}")
}
