// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					AwsNeuronDeviceHostMemoryUsage: AwsNeuronDeviceHostMemoryUsageMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronDeviceHostMemoryUsageMetricAttributeKey{AwsNeuronDeviceHostMemoryUsageMetricAttributeKeyMemoryCategory, AwsNeuronDeviceHostMemoryUsageMetricAttributeKeyMemoryState},
					},
					AwsNeuronDevicePowerUtilization: AwsNeuronDevicePowerUtilizationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AwsNeuronDevicePowerUtilizationMetricAttributeKey{AwsNeuronDevicePowerUtilizationMetricAttributeKeyPowerStatistic},
					},
					AwsNeuronErrors: AwsNeuronErrorsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronErrorsMetricAttributeKey{AwsNeuronErrorsMetricAttributeKeyHwID, AwsNeuronErrorsMetricAttributeKeyMemoryType, AwsNeuronErrorsMetricAttributeKeyErrorType},
					},
					AwsNeuronExecutionCount: AwsNeuronExecutionCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronExecutionCountMetricAttributeKey{AwsNeuronExecutionCountMetricAttributeKeyExecutionStatus},
					},
					AwsNeuronExecutionErrors: AwsNeuronExecutionErrorsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronExecutionErrorsMetricAttributeKey{AwsNeuronExecutionErrorsMetricAttributeKeyErrorType},
					},
					AwsNeuronExecutionLatency: AwsNeuronExecutionLatencyMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AwsNeuronExecutionLatencyMetricAttributeKey{AwsNeuronExecutionLatencyMetricAttributeKeyLatencyType, AwsNeuronExecutionLatencyMetricAttributeKeyQuantile},
					},
					AwsNeuronNeuroncoreDeviceMemoryUsage: AwsNeuronNeuroncoreDeviceMemoryUsageMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronNeuroncoreDeviceMemoryUsageMetricAttributeKey{AwsNeuronNeuroncoreDeviceMemoryUsageMetricAttributeKeyNeuroncore, AwsNeuronNeuroncoreDeviceMemoryUsageMetricAttributeKeyMemoryCategory, AwsNeuronNeuroncoreDeviceMemoryUsageMetricAttributeKeyMemoryState},
					},
					AwsNeuronNeuroncoreFlops: AwsNeuronNeuroncoreFlopsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AwsNeuronNeuroncoreFlopsMetricAttributeKey{AwsNeuronNeuroncoreFlopsMetricAttributeKeyNeuroncore},
					},
					AwsNeuronNeuroncoreHostMemoryUsage: AwsNeuronNeuroncoreHostMemoryUsageMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronNeuroncoreHostMemoryUsageMetricAttributeKey{AwsNeuronNeuroncoreHostMemoryUsageMetricAttributeKeyNeuroncore, AwsNeuronNeuroncoreHostMemoryUsageMetricAttributeKeyMemoryState},
					},
					AwsNeuronNeuroncoreInferences: AwsNeuronNeuroncoreInferencesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronNeuroncoreInferencesMetricAttributeKey{AwsNeuronNeuroncoreInferencesMetricAttributeKeyNeuroncore},
					},
					AwsNeuronNeuroncoreMemoryUsage: AwsNeuronNeuroncoreMemoryUsageMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronNeuroncoreMemoryUsageMetricAttributeKey{AwsNeuronNeuroncoreMemoryUsageMetricAttributeKeyNeuroncore, AwsNeuronNeuroncoreMemoryUsageMetricAttributeKeyMemoryCategory},
					},
					AwsNeuronNeuroncoreStatus: AwsNeuronNeuroncoreStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronNeuroncoreStatusMetricAttributeKey{AwsNeuronNeuroncoreStatusMetricAttributeKeyNeuroncore, AwsNeuronNeuroncoreStatusMetricAttributeKeyStatus},
					},
					AwsNeuronNeuroncoreTimeInUse: AwsNeuronNeuroncoreTimeInUseMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronNeuroncoreTimeInUseMetricAttributeKey{AwsNeuronNeuroncoreTimeInUseMetricAttributeKeyNeuroncore},
					},
					AwsNeuronNeuroncoreUtilization: AwsNeuronNeuroncoreUtilizationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AwsNeuronNeuroncoreUtilizationMetricAttributeKey{AwsNeuronNeuroncoreUtilizationMetricAttributeKeyNeuroncore},
					},
					AwsNeuronRuntimeMemoryUsage: AwsNeuronRuntimeMemoryUsageMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronRuntimeMemoryUsageMetricAttributeKey{AwsNeuronRuntimeMemoryUsageMetricAttributeKeyMemoryType},
					},
					AwsNeuronRuntimeVcpuUtilization: AwsNeuronRuntimeVcpuUtilizationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AwsNeuronRuntimeVcpuUtilizationMetricAttributeKey{AwsNeuronRuntimeVcpuUtilizationMetricAttributeKeyCPUState},
					},
					AwsNeuronSystemCPUUtilization: AwsNeuronSystemCPUUtilizationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AwsNeuronSystemCPUUtilizationMetricAttributeKey{AwsNeuronSystemCPUUtilizationMetricAttributeKeyCPU, AwsNeuronSystemCPUUtilizationMetricAttributeKeyCPUState},
					},
					AwsNeuronSystemMemoryUsage: AwsNeuronSystemMemoryUsageMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronSystemMemoryUsageMetricAttributeKey{AwsNeuronSystemMemoryUsageMetricAttributeKeyMemoryType},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					AwsNeuronDeviceType:        ResourceAttributeConfig{Enabled: true},
					AwsNeuronNeuroncoreVersion: ResourceAttributeConfig{Enabled: true},
					CloudAvailabilityZone:      ResourceAttributeConfig{Enabled: true},
					CloudProvider:              ResourceAttributeConfig{Enabled: true},
					CloudRegion:                ResourceAttributeConfig{Enabled: true},
					HostID:                     ResourceAttributeConfig{Enabled: true},
					HostType:                   ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					AwsNeuronDeviceHostMemoryUsage: AwsNeuronDeviceHostMemoryUsageMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronDeviceHostMemoryUsageMetricAttributeKey{AwsNeuronDeviceHostMemoryUsageMetricAttributeKeyMemoryCategory, AwsNeuronDeviceHostMemoryUsageMetricAttributeKeyMemoryState},
					},
					AwsNeuronDevicePowerUtilization: AwsNeuronDevicePowerUtilizationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AwsNeuronDevicePowerUtilizationMetricAttributeKey{AwsNeuronDevicePowerUtilizationMetricAttributeKeyPowerStatistic},
					},
					AwsNeuronErrors: AwsNeuronErrorsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronErrorsMetricAttributeKey{AwsNeuronErrorsMetricAttributeKeyHwID, AwsNeuronErrorsMetricAttributeKeyMemoryType, AwsNeuronErrorsMetricAttributeKeyErrorType},
					},
					AwsNeuronExecutionCount: AwsNeuronExecutionCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronExecutionCountMetricAttributeKey{AwsNeuronExecutionCountMetricAttributeKeyExecutionStatus},
					},
					AwsNeuronExecutionErrors: AwsNeuronExecutionErrorsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronExecutionErrorsMetricAttributeKey{AwsNeuronExecutionErrorsMetricAttributeKeyErrorType},
					},
					AwsNeuronExecutionLatency: AwsNeuronExecutionLatencyMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AwsNeuronExecutionLatencyMetricAttributeKey{AwsNeuronExecutionLatencyMetricAttributeKeyLatencyType, AwsNeuronExecutionLatencyMetricAttributeKeyQuantile},
					},
					AwsNeuronNeuroncoreDeviceMemoryUsage: AwsNeuronNeuroncoreDeviceMemoryUsageMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronNeuroncoreDeviceMemoryUsageMetricAttributeKey{AwsNeuronNeuroncoreDeviceMemoryUsageMetricAttributeKeyNeuroncore, AwsNeuronNeuroncoreDeviceMemoryUsageMetricAttributeKeyMemoryCategory, AwsNeuronNeuroncoreDeviceMemoryUsageMetricAttributeKeyMemoryState},
					},
					AwsNeuronNeuroncoreFlops: AwsNeuronNeuroncoreFlopsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AwsNeuronNeuroncoreFlopsMetricAttributeKey{AwsNeuronNeuroncoreFlopsMetricAttributeKeyNeuroncore},
					},
					AwsNeuronNeuroncoreHostMemoryUsage: AwsNeuronNeuroncoreHostMemoryUsageMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronNeuroncoreHostMemoryUsageMetricAttributeKey{AwsNeuronNeuroncoreHostMemoryUsageMetricAttributeKeyNeuroncore, AwsNeuronNeuroncoreHostMemoryUsageMetricAttributeKeyMemoryState},
					},
					AwsNeuronNeuroncoreInferences: AwsNeuronNeuroncoreInferencesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronNeuroncoreInferencesMetricAttributeKey{AwsNeuronNeuroncoreInferencesMetricAttributeKeyNeuroncore},
					},
					AwsNeuronNeuroncoreMemoryUsage: AwsNeuronNeuroncoreMemoryUsageMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronNeuroncoreMemoryUsageMetricAttributeKey{AwsNeuronNeuroncoreMemoryUsageMetricAttributeKeyNeuroncore, AwsNeuronNeuroncoreMemoryUsageMetricAttributeKeyMemoryCategory},
					},
					AwsNeuronNeuroncoreStatus: AwsNeuronNeuroncoreStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronNeuroncoreStatusMetricAttributeKey{AwsNeuronNeuroncoreStatusMetricAttributeKeyNeuroncore, AwsNeuronNeuroncoreStatusMetricAttributeKeyStatus},
					},
					AwsNeuronNeuroncoreTimeInUse: AwsNeuronNeuroncoreTimeInUseMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronNeuroncoreTimeInUseMetricAttributeKey{AwsNeuronNeuroncoreTimeInUseMetricAttributeKeyNeuroncore},
					},
					AwsNeuronNeuroncoreUtilization: AwsNeuronNeuroncoreUtilizationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AwsNeuronNeuroncoreUtilizationMetricAttributeKey{AwsNeuronNeuroncoreUtilizationMetricAttributeKeyNeuroncore},
					},
					AwsNeuronRuntimeMemoryUsage: AwsNeuronRuntimeMemoryUsageMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronRuntimeMemoryUsageMetricAttributeKey{AwsNeuronRuntimeMemoryUsageMetricAttributeKeyMemoryType},
					},
					AwsNeuronRuntimeVcpuUtilization: AwsNeuronRuntimeVcpuUtilizationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AwsNeuronRuntimeVcpuUtilizationMetricAttributeKey{AwsNeuronRuntimeVcpuUtilizationMetricAttributeKeyCPUState},
					},
					AwsNeuronSystemCPUUtilization: AwsNeuronSystemCPUUtilizationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []AwsNeuronSystemCPUUtilizationMetricAttributeKey{AwsNeuronSystemCPUUtilizationMetricAttributeKeyCPU, AwsNeuronSystemCPUUtilizationMetricAttributeKeyCPUState},
					},
					AwsNeuronSystemMemoryUsage: AwsNeuronSystemMemoryUsageMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []AwsNeuronSystemMemoryUsageMetricAttributeKey{AwsNeuronSystemMemoryUsageMetricAttributeKeyMemoryType},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					AwsNeuronDeviceType:        ResourceAttributeConfig{Enabled: false},
					AwsNeuronNeuroncoreVersion: ResourceAttributeConfig{Enabled: false},
					CloudAvailabilityZone:      ResourceAttributeConfig{Enabled: false},
					CloudProvider:              ResourceAttributeConfig{Enabled: false},
					CloudRegion:                ResourceAttributeConfig{Enabled: false},
					HostID:                     ResourceAttributeConfig{Enabled: false},
					HostType:                   ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(AwsNeuronDeviceHostMemoryUsageMetricConfig{}, AwsNeuronDevicePowerUtilizationMetricConfig{}, AwsNeuronErrorsMetricConfig{}, AwsNeuronExecutionCountMetricConfig{}, AwsNeuronExecutionErrorsMetricConfig{}, AwsNeuronExecutionLatencyMetricConfig{}, AwsNeuronNeuroncoreDeviceMemoryUsageMetricConfig{}, AwsNeuronNeuroncoreFlopsMetricConfig{}, AwsNeuronNeuroncoreHostMemoryUsageMetricConfig{}, AwsNeuronNeuroncoreInferencesMetricConfig{}, AwsNeuronNeuroncoreMemoryUsageMetricConfig{}, AwsNeuronNeuroncoreStatusMetricConfig{}, AwsNeuronNeuroncoreTimeInUseMetricConfig{}, AwsNeuronNeuroncoreUtilizationMetricConfig{}, AwsNeuronRuntimeMemoryUsageMetricConfig{}, AwsNeuronRuntimeVcpuUtilizationMetricConfig{}, AwsNeuronSystemCPUUtilizationMetricConfig{}, AwsNeuronSystemMemoryUsageMetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}
func TestAwsNeuronDeviceHostMemoryUsageMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronDeviceHostMemoryUsage
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronDeviceHostMemoryUsageMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.device.host_memory.usage doesn't have an attribute invalid, valid attributes: [aws.neuron.memory.category, aws.neuron.memory.state]")

	cfg = DefaultMetricsConfig().AwsNeuronDeviceHostMemoryUsage
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronDevicePowerUtilizationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronDevicePowerUtilization
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronDevicePowerUtilizationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.device.power.utilization doesn't have an attribute invalid, valid attributes: [aws.neuron.power.statistic]")

	cfg = DefaultMetricsConfig().AwsNeuronDevicePowerUtilization
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronErrorsMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronErrors
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronErrorsMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.errors doesn't have an attribute invalid, valid attributes: [hw.id, aws.neuron.memory.type, error.type]")

	cfg = DefaultMetricsConfig().AwsNeuronErrors
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronExecutionCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronExecutionCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronExecutionCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.execution.count doesn't have an attribute invalid, valid attributes: [aws.neuron.execution.status]")

	cfg = DefaultMetricsConfig().AwsNeuronExecutionCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronExecutionErrorsMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronExecutionErrors
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronExecutionErrorsMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.execution.errors doesn't have an attribute invalid, valid attributes: [error.type]")

	cfg = DefaultMetricsConfig().AwsNeuronExecutionErrors
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronExecutionLatencyMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronExecutionLatency
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronExecutionLatencyMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.execution.latency doesn't have an attribute invalid, valid attributes: [aws.neuron.latency.type, aws.neuron.latency.quantile]")

	cfg = DefaultMetricsConfig().AwsNeuronExecutionLatency
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronNeuroncoreDeviceMemoryUsageMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronNeuroncoreDeviceMemoryUsage
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronNeuroncoreDeviceMemoryUsageMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.neuroncore.device_memory.usage doesn't have an attribute invalid, valid attributes: [aws.neuron.neuroncore.id, aws.neuron.memory.category, aws.neuron.memory.state]")

	cfg = DefaultMetricsConfig().AwsNeuronNeuroncoreDeviceMemoryUsage
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronNeuroncoreFlopsMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronNeuroncoreFlops
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronNeuroncoreFlopsMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.neuroncore.flops doesn't have an attribute invalid, valid attributes: [aws.neuron.neuroncore.id]")

	cfg = DefaultMetricsConfig().AwsNeuronNeuroncoreFlops
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronNeuroncoreHostMemoryUsageMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronNeuroncoreHostMemoryUsage
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronNeuroncoreHostMemoryUsageMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.neuroncore.host_memory.usage doesn't have an attribute invalid, valid attributes: [aws.neuron.neuroncore.id, aws.neuron.memory.state]")

	cfg = DefaultMetricsConfig().AwsNeuronNeuroncoreHostMemoryUsage
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronNeuroncoreInferencesMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronNeuroncoreInferences
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronNeuroncoreInferencesMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.neuroncore.inferences doesn't have an attribute invalid, valid attributes: [aws.neuron.neuroncore.id]")

	cfg = DefaultMetricsConfig().AwsNeuronNeuroncoreInferences
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronNeuroncoreMemoryUsageMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronNeuroncoreMemoryUsage
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronNeuroncoreMemoryUsageMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.neuroncore.memory.usage doesn't have an attribute invalid, valid attributes: [aws.neuron.neuroncore.id, aws.neuron.memory.category]")

	cfg = DefaultMetricsConfig().AwsNeuronNeuroncoreMemoryUsage
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronNeuroncoreStatusMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronNeuroncoreStatus
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronNeuroncoreStatusMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.neuroncore.status doesn't have an attribute invalid, valid attributes: [aws.neuron.neuroncore.id, aws.neuron.neuroncore.status]")

	cfg = DefaultMetricsConfig().AwsNeuronNeuroncoreStatus
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronNeuroncoreTimeInUseMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronNeuroncoreTimeInUse
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronNeuroncoreTimeInUseMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.neuroncore.time_in_use doesn't have an attribute invalid, valid attributes: [aws.neuron.neuroncore.id]")

	cfg = DefaultMetricsConfig().AwsNeuronNeuroncoreTimeInUse
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronNeuroncoreUtilizationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronNeuroncoreUtilization
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronNeuroncoreUtilizationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.neuroncore.utilization doesn't have an attribute invalid, valid attributes: [aws.neuron.neuroncore.id]")

	cfg = DefaultMetricsConfig().AwsNeuronNeuroncoreUtilization
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronRuntimeMemoryUsageMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronRuntimeMemoryUsage
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronRuntimeMemoryUsageMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.runtime.memory.usage doesn't have an attribute invalid, valid attributes: [aws.neuron.memory.type]")

	cfg = DefaultMetricsConfig().AwsNeuronRuntimeMemoryUsage
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronRuntimeVcpuUtilizationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronRuntimeVcpuUtilization
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronRuntimeVcpuUtilizationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.runtime.vcpu.utilization doesn't have an attribute invalid, valid attributes: [aws.neuron.cpu.state]")

	cfg = DefaultMetricsConfig().AwsNeuronRuntimeVcpuUtilization
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronSystemCPUUtilizationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronSystemCPUUtilization
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronSystemCPUUtilizationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.system.cpu.utilization doesn't have an attribute invalid, valid attributes: [aws.neuron.cpu.logical_number, aws.neuron.cpu.state]")

	cfg = DefaultMetricsConfig().AwsNeuronSystemCPUUtilization
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestAwsNeuronSystemMemoryUsageMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().AwsNeuronSystemMemoryUsage
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []AwsNeuronSystemMemoryUsageMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric aws.neuron.system.memory.usage doesn't have an attribute invalid, valid attributes: [aws.neuron.memory.type]")

	cfg = DefaultMetricsConfig().AwsNeuronSystemMemoryUsage
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				AwsNeuronDeviceType:        ResourceAttributeConfig{Enabled: true},
				AwsNeuronNeuroncoreVersion: ResourceAttributeConfig{Enabled: true},
				CloudAvailabilityZone:      ResourceAttributeConfig{Enabled: true},
				CloudProvider:              ResourceAttributeConfig{Enabled: true},
				CloudRegion:                ResourceAttributeConfig{Enabled: true},
				HostID:                     ResourceAttributeConfig{Enabled: true},
				HostType:                   ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				AwsNeuronDeviceType:        ResourceAttributeConfig{Enabled: false},
				AwsNeuronNeuroncoreVersion: ResourceAttributeConfig{Enabled: false},
				CloudAvailabilityZone:      ResourceAttributeConfig{Enabled: false},
				CloudProvider:              ResourceAttributeConfig{Enabled: false},
				CloudRegion:                ResourceAttributeConfig{Enabled: false},
				HostID:                     ResourceAttributeConfig{Enabled: false},
				HostType:                   ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
