// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
	testDataSetReag
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "reaggregate_set",
			metricsSet:  testDataSetReag,
			resAttrsSet: testDataSetReag,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: testDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))
			aggMap := make(map[string]string) // contains the aggregation strategies for each metric name
			aggMap["aws.neuron.device.host_memory.usage"] = mb.metricAwsNeuronDeviceHostMemoryUsage.config.AggregationStrategy
			aggMap["aws.neuron.device.power.utilization"] = mb.metricAwsNeuronDevicePowerUtilization.config.AggregationStrategy
			aggMap["aws.neuron.errors"] = mb.metricAwsNeuronErrors.config.AggregationStrategy
			aggMap["aws.neuron.execution.count"] = mb.metricAwsNeuronExecutionCount.config.AggregationStrategy
			aggMap["aws.neuron.execution.errors"] = mb.metricAwsNeuronExecutionErrors.config.AggregationStrategy
			aggMap["aws.neuron.execution.latency"] = mb.metricAwsNeuronExecutionLatency.config.AggregationStrategy
			aggMap["aws.neuron.neuroncore.device_memory.usage"] = mb.metricAwsNeuronNeuroncoreDeviceMemoryUsage.config.AggregationStrategy
			aggMap["aws.neuron.neuroncore.flops"] = mb.metricAwsNeuronNeuroncoreFlops.config.AggregationStrategy
			aggMap["aws.neuron.neuroncore.host_memory.usage"] = mb.metricAwsNeuronNeuroncoreHostMemoryUsage.config.AggregationStrategy
			aggMap["aws.neuron.neuroncore.inferences"] = mb.metricAwsNeuronNeuroncoreInferences.config.AggregationStrategy
			aggMap["aws.neuron.neuroncore.memory.usage"] = mb.metricAwsNeuronNeuroncoreMemoryUsage.config.AggregationStrategy
			aggMap["aws.neuron.neuroncore.status"] = mb.metricAwsNeuronNeuroncoreStatus.config.AggregationStrategy
			aggMap["aws.neuron.neuroncore.time_in_use"] = mb.metricAwsNeuronNeuroncoreTimeInUse.config.AggregationStrategy
			aggMap["aws.neuron.neuroncore.utilization"] = mb.metricAwsNeuronNeuroncoreUtilization.config.AggregationStrategy
			aggMap["aws.neuron.runtime.memory.usage"] = mb.metricAwsNeuronRuntimeMemoryUsage.config.AggregationStrategy
			aggMap["aws.neuron.runtime.vcpu.utilization"] = mb.metricAwsNeuronRuntimeVcpuUtilization.config.AggregationStrategy
			aggMap["aws.neuron.system.cpu.utilization"] = mb.metricAwsNeuronSystemCPUUtilization.config.AggregationStrategy
			aggMap["aws.neuron.system.memory.usage"] = mb.metricAwsNeuronSystemMemoryUsage.config.AggregationStrategy

			expectedWarnings := 0
			if tt.metricsSet != testDataSetReag {
				assert.Equal(t, expectedWarnings, observedLogs.Len())
			}

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAwsNeuronDeviceHostMemoryUsageDataPoint(ts, 1, "memory_category-val", AttributeMemoryStatePresent)
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronDeviceHostMemoryUsageDataPoint(ts, 3, "memory_category-val-2", AttributeMemoryStatePeak)
			}

			allMetricsCount++
			mb.RecordAwsNeuronDevicePowerUtilizationDataPoint(ts, 1, AttributePowerStatisticMin)
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronDevicePowerUtilizationDataPoint(ts, 3, AttributePowerStatisticMax)
			}

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAwsNeuronErrorsDataPoint(ts, 1, "hw_id-val", "memory_type-val", "error_type-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronErrorsDataPoint(ts, 3, "hw_id-val-2", "memory_type-val-2", "error_type-val-2")
			}

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAwsNeuronExecutionCountDataPoint(ts, 1, "execution_status-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronExecutionCountDataPoint(ts, 3, "execution_status-val-2")
			}

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAwsNeuronExecutionErrorsDataPoint(ts, 1, "error_type-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronExecutionErrorsDataPoint(ts, 3, "error_type-val-2")
			}

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAwsNeuronExecutionLatencyDataPoint(ts, 1, AttributeLatencyTypeTotal, "quantile-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronExecutionLatencyDataPoint(ts, 3, AttributeLatencyTypeDevice, "quantile-val-2")
			}

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAwsNeuronNeuroncoreDeviceMemoryUsageDataPoint(ts, 1, 10, "memory_category-val", AttributeMemoryStatePresent)
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronNeuroncoreDeviceMemoryUsageDataPoint(ts, 3, 11, "memory_category-val-2", AttributeMemoryStatePeak)
			}

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAwsNeuronNeuroncoreFlopsDataPoint(ts, 1, 10)
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronNeuroncoreFlopsDataPoint(ts, 3, 11)
			}

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAwsNeuronNeuroncoreHostMemoryUsageDataPoint(ts, 1, 10, AttributeMemoryStatePresent)
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronNeuroncoreHostMemoryUsageDataPoint(ts, 3, 11, AttributeMemoryStatePeak)
			}

			allMetricsCount++
			mb.RecordAwsNeuronNeuroncoreInferencesDataPoint(ts, 1, 10)
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronNeuroncoreInferencesDataPoint(ts, 3, 11)
			}

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAwsNeuronNeuroncoreMemoryUsageDataPoint(ts, 1, 10, "memory_category-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronNeuroncoreMemoryUsageDataPoint(ts, 3, 11, "memory_category-val-2")
			}

			allMetricsCount++
			mb.RecordAwsNeuronNeuroncoreStatusDataPoint(ts, 1, 10, "status-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronNeuroncoreStatusDataPoint(ts, 3, 11, "status-val-2")
			}

			allMetricsCount++
			mb.RecordAwsNeuronNeuroncoreTimeInUseDataPoint(ts, 1, 10)
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronNeuroncoreTimeInUseDataPoint(ts, 3, 11)
			}

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAwsNeuronNeuroncoreUtilizationDataPoint(ts, 1, 10)
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronNeuroncoreUtilizationDataPoint(ts, 3, 11)
			}

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordAwsNeuronRuntimeMemoryUsageDataPoint(ts, 1, "memory_type-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronRuntimeMemoryUsageDataPoint(ts, 3, "memory_type-val-2")
			}

			allMetricsCount++
			mb.RecordAwsNeuronRuntimeVcpuUtilizationDataPoint(ts, 1, "cpu_state-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronRuntimeVcpuUtilizationDataPoint(ts, 3, "cpu_state-val-2")
			}

			allMetricsCount++
			mb.RecordAwsNeuronSystemCPUUtilizationDataPoint(ts, 1, "cpu-val", "cpu_state-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronSystemCPUUtilizationDataPoint(ts, 3, "cpu-val-2", "cpu_state-val-2")
			}

			allMetricsCount++
			mb.RecordAwsNeuronSystemMemoryUsageDataPoint(ts, 1, "memory_type-val")
			if tt.name == "reaggregate_set" {
				mb.RecordAwsNeuronSystemMemoryUsageDataPoint(ts, 3, "memory_type-val-2")
			}

			rb := mb.NewResourceBuilder()
			rb.SetAwsNeuronDeviceType("aws.neuron.device.type-val")
			rb.SetAwsNeuronNeuroncoreVersion("aws.neuron.neuroncore.version-val")
			rb.SetCloudAvailabilityZone("cloud.availability_zone-val")
			rb.SetCloudProvider("cloud.provider-val")
			rb.SetCloudRegion("cloud.region-val")
			rb.SetHostID("host.id-val")
			rb.SetHostType("host.type-val")
			res := rb.Emit()
			metrics := mb.Emit(WithResource(res))
			if tt.name == "reaggregate_set" {
				assert.Empty(t, mb.metricAwsNeuronDeviceHostMemoryUsage.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronDevicePowerUtilization.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronErrors.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronExecutionCount.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronExecutionErrors.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronExecutionLatency.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronNeuroncoreDeviceMemoryUsage.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronNeuroncoreFlops.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronNeuroncoreHostMemoryUsage.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronNeuroncoreInferences.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronNeuroncoreMemoryUsage.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronNeuroncoreStatus.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronNeuroncoreTimeInUse.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronNeuroncoreUtilization.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronRuntimeMemoryUsage.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronRuntimeVcpuUtilization.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronSystemCPUUtilization.aggDataPoints)
				assert.Empty(t, mb.metricAwsNeuronSystemMemoryUsage.aggDataPoints)
			}

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "aws.neuron.device.host_memory.usage":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.device.host_memory.usage"], "Found a duplicate in the metrics slice: aws.neuron.device.host_memory.usage")
						validatedMetrics["aws.neuron.device.host_memory.usage"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Device-level host memory by sysfs category (present and peak).", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.False(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						memoryCategoryAttrVal, ok := dp.Attributes().Get("aws.neuron.memory.category")
						assert.True(t, ok)
						assert.Equal(t, "memory_category-val", memoryCategoryAttrVal.Str())
						memoryStateAttrVal, ok := dp.Attributes().Get("aws.neuron.memory.state")
						assert.True(t, ok)
						assert.Equal(t, "present", memoryStateAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.device.host_memory.usage"], "Found a duplicate in the metrics slice: aws.neuron.device.host_memory.usage")
						validatedMetrics["aws.neuron.device.host_memory.usage"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Device-level host memory by sysfs category (present and peak).", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.False(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["aws.neuron.device.host_memory.usage"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("aws.neuron.memory.category")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("aws.neuron.memory.state")
						assert.False(t, ok)
					}
				case "aws.neuron.device.power.utilization":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.device.power.utilization"], "Found a duplicate in the metrics slice: aws.neuron.device.power.utilization")
						validatedMetrics["aws.neuron.device.power.utilization"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Device power utilization (fraction of max power) from sysfs, split by statistic over the sampling period (best-effort; not populated on all instances).", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						powerStatisticAttrVal, ok := dp.Attributes().Get("aws.neuron.power.statistic")
						assert.True(t, ok)
						assert.Equal(t, "min", powerStatisticAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.device.power.utilization"], "Found a duplicate in the metrics slice: aws.neuron.device.power.utilization")
						validatedMetrics["aws.neuron.device.power.utilization"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Device power utilization (fraction of max power) from sysfs, split by statistic over the sampling period (best-effort; not populated on all instances).", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["aws.neuron.device.power.utilization"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("aws.neuron.power.statistic")
						assert.False(t, ok)
					}
				case "aws.neuron.errors":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.errors"], "Found a duplicate in the metrics slice: aws.neuron.errors")
						validatedMetrics["aws.neuron.errors"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Cumulative ECC errors from Neuron hardware counters (neuron-monitor or sysfs).", mi.Description())
						assert.Equal(t, "{error}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
						assert.True(t, ok)
						assert.Equal(t, "hw_id-val", hwIDAttrVal.Str())
						memoryTypeAttrVal, ok := dp.Attributes().Get("aws.neuron.memory.type")
						assert.True(t, ok)
						assert.Equal(t, "memory_type-val", memoryTypeAttrVal.Str())
						errorTypeAttrVal, ok := dp.Attributes().Get("error.type")
						assert.True(t, ok)
						assert.Equal(t, "error_type-val", errorTypeAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.errors"], "Found a duplicate in the metrics slice: aws.neuron.errors")
						validatedMetrics["aws.neuron.errors"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Cumulative ECC errors from Neuron hardware counters (neuron-monitor or sysfs).", mi.Description())
						assert.Equal(t, "{error}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["aws.neuron.errors"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("hw.id")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("aws.neuron.memory.type")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("error.type")
						assert.False(t, ok)
					}
				case "aws.neuron.execution.count":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.execution.count"], "Found a duplicate in the metrics slice: aws.neuron.execution.count")
						validatedMetrics["aws.neuron.execution.count"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Executions on the NeuronCore in the collection period, by outcome.", mi.Description())
						assert.Equal(t, "{execution}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						executionStatusAttrVal, ok := dp.Attributes().Get("aws.neuron.execution.status")
						assert.True(t, ok)
						assert.Equal(t, "execution_status-val", executionStatusAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.execution.count"], "Found a duplicate in the metrics slice: aws.neuron.execution.count")
						validatedMetrics["aws.neuron.execution.count"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Executions on the NeuronCore in the collection period, by outcome.", mi.Description())
						assert.Equal(t, "{execution}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["aws.neuron.execution.count"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("aws.neuron.execution.status")
						assert.False(t, ok)
					}
				case "aws.neuron.execution.errors":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.execution.errors"], "Found a duplicate in the metrics slice: aws.neuron.execution.errors")
						validatedMetrics["aws.neuron.execution.errors"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Execution errors on the NeuronCore in the collection period.", mi.Description())
						assert.Equal(t, "{error}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						errorTypeAttrVal, ok := dp.Attributes().Get("error.type")
						assert.True(t, ok)
						assert.Equal(t, "error_type-val", errorTypeAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.execution.errors"], "Found a duplicate in the metrics slice: aws.neuron.execution.errors")
						validatedMetrics["aws.neuron.execution.errors"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Execution errors on the NeuronCore in the collection period.", mi.Description())
						assert.Equal(t, "{error}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["aws.neuron.execution.errors"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("error.type")
						assert.False(t, ok)
					}
				case "aws.neuron.execution.latency":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.execution.latency"], "Found a duplicate in the metrics slice: aws.neuron.execution.latency")
						validatedMetrics["aws.neuron.execution.latency"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Execution latency percentiles reported by neuron-monitor.", mi.Description())
						assert.Equal(t, "s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						latencyTypeAttrVal, ok := dp.Attributes().Get("aws.neuron.latency.type")
						assert.True(t, ok)
						assert.Equal(t, "total", latencyTypeAttrVal.Str())
						quantileAttrVal, ok := dp.Attributes().Get("aws.neuron.latency.quantile")
						assert.True(t, ok)
						assert.Equal(t, "quantile-val", quantileAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.execution.latency"], "Found a duplicate in the metrics slice: aws.neuron.execution.latency")
						validatedMetrics["aws.neuron.execution.latency"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Execution latency percentiles reported by neuron-monitor.", mi.Description())
						assert.Equal(t, "s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["aws.neuron.execution.latency"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("aws.neuron.latency.type")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("aws.neuron.latency.quantile")
						assert.False(t, ok)
					}
				case "aws.neuron.neuroncore.device_memory.usage":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.neuroncore.device_memory.usage"], "Found a duplicate in the metrics slice: aws.neuron.neuroncore.device_memory.usage")
						validatedMetrics["aws.neuron.neuroncore.device_memory.usage"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Device memory per NeuronCore by fine-grained sysfs category (present and peak).", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.False(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						neuroncoreAttrVal, ok := dp.Attributes().Get("aws.neuron.neuroncore.id")
						assert.True(t, ok)
						assert.EqualValues(t, 10, neuroncoreAttrVal.Int())
						memoryCategoryAttrVal, ok := dp.Attributes().Get("aws.neuron.memory.category")
						assert.True(t, ok)
						assert.Equal(t, "memory_category-val", memoryCategoryAttrVal.Str())
						memoryStateAttrVal, ok := dp.Attributes().Get("aws.neuron.memory.state")
						assert.True(t, ok)
						assert.Equal(t, "present", memoryStateAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.neuroncore.device_memory.usage"], "Found a duplicate in the metrics slice: aws.neuron.neuroncore.device_memory.usage")
						validatedMetrics["aws.neuron.neuroncore.device_memory.usage"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Device memory per NeuronCore by fine-grained sysfs category (present and peak).", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.False(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["aws.neuron.neuroncore.device_memory.usage"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("aws.neuron.neuroncore.id")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("aws.neuron.memory.category")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("aws.neuron.memory.state")
						assert.False(t, ok)
					}
				case "aws.neuron.neuroncore.flops":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.neuroncore.flops"], "Found a duplicate in the metrics slice: aws.neuron.neuroncore.flops")
						validatedMetrics["aws.neuron.neuroncore.flops"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Effective floating point operations per second on the NeuronCore.", mi.Description())
						assert.Equal(t, "{flop}/s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						neuroncoreAttrVal, ok := dp.Attributes().Get("aws.neuron.neuroncore.id")
						assert.True(t, ok)
						assert.EqualValues(t, 10, neuroncoreAttrVal.Int())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.neuroncore.flops"], "Found a duplicate in the metrics slice: aws.neuron.neuroncore.flops")
						validatedMetrics["aws.neuron.neuroncore.flops"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Effective floating point operations per second on the NeuronCore.", mi.Description())
						assert.Equal(t, "{flop}/s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["aws.neuron.neuroncore.flops"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("aws.neuron.neuroncore.id")
						assert.False(t, ok)
					}
				case "aws.neuron.neuroncore.host_memory.usage":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.neuroncore.host_memory.usage"], "Found a duplicate in the metrics slice: aws.neuron.neuroncore.host_memory.usage")
						validatedMetrics["aws.neuron.neuroncore.host_memory.usage"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Host memory attributed to each NeuronCore from sysfs (present and peak).", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.False(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						neuroncoreAttrVal, ok := dp.Attributes().Get("aws.neuron.neuroncore.id")
						assert.True(t, ok)
						assert.EqualValues(t, 10, neuroncoreAttrVal.Int())
						memoryStateAttrVal, ok := dp.Attributes().Get("aws.neuron.memory.state")
						assert.True(t, ok)
						assert.Equal(t, "present", memoryStateAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.neuroncore.host_memory.usage"], "Found a duplicate in the metrics slice: aws.neuron.neuroncore.host_memory.usage")
						validatedMetrics["aws.neuron.neuroncore.host_memory.usage"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Host memory attributed to each NeuronCore from sysfs (present and peak).", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.False(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["aws.neuron.neuroncore.host_memory.usage"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("aws.neuron.neuroncore.id")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("aws.neuron.memory.state")
						assert.False(t, ok)
					}
				case "aws.neuron.neuroncore.inferences":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.neuroncore.inferences"], "Found a duplicate in the metrics slice: aws.neuron.neuroncore.inferences")
						validatedMetrics["aws.neuron.neuroncore.inferences"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Inference count from sysfs (runtime-gated; usually zero).", mi.Description())
						assert.Equal(t, "{inference}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						neuroncoreAttrVal, ok := dp.Attributes().Get("aws.neuron.neuroncore.id")
						assert.True(t, ok)
						assert.EqualValues(t, 10, neuroncoreAttrVal.Int())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.neuroncore.inferences"], "Found a duplicate in the metrics slice: aws.neuron.neuroncore.inferences")
						validatedMetrics["aws.neuron.neuroncore.inferences"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Inference count from sysfs (runtime-gated; usually zero).", mi.Description())
						assert.Equal(t, "{inference}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["aws.neuron.neuroncore.inferences"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("aws.neuron.neuroncore.id")
						assert.False(t, ok)
					}
				case "aws.neuron.neuroncore.memory.usage":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.neuroncore.memory.usage"], "Found a duplicate in the metrics slice: aws.neuron.neuroncore.memory.usage")
						validatedMetrics["aws.neuron.neuroncore.memory.usage"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Device memory used per NeuronCore by category (neuron-monitor aggregate view).", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.False(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						neuroncoreAttrVal, ok := dp.Attributes().Get("aws.neuron.neuroncore.id")
						assert.True(t, ok)
						assert.EqualValues(t, 10, neuroncoreAttrVal.Int())
						memoryCategoryAttrVal, ok := dp.Attributes().Get("aws.neuron.memory.category")
						assert.True(t, ok)
						assert.Equal(t, "memory_category-val", memoryCategoryAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.neuroncore.memory.usage"], "Found a duplicate in the metrics slice: aws.neuron.neuroncore.memory.usage")
						validatedMetrics["aws.neuron.neuroncore.memory.usage"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Device memory used per NeuronCore by category (neuron-monitor aggregate view).", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.False(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["aws.neuron.neuroncore.memory.usage"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("aws.neuron.neuroncore.id")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("aws.neuron.memory.category")
						assert.False(t, ok)
					}
				case "aws.neuron.neuroncore.status":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.neuroncore.status"], "Found a duplicate in the metrics slice: aws.neuron.neuroncore.status")
						validatedMetrics["aws.neuron.neuroncore.status"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "sysfs per-NeuronCore status/error counters (runtime-gated; usually zero).", mi.Description())
						assert.Equal(t, "{event}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						neuroncoreAttrVal, ok := dp.Attributes().Get("aws.neuron.neuroncore.id")
						assert.True(t, ok)
						assert.EqualValues(t, 10, neuroncoreAttrVal.Int())
						statusAttrVal, ok := dp.Attributes().Get("aws.neuron.neuroncore.status")
						assert.True(t, ok)
						assert.Equal(t, "status-val", statusAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.neuroncore.status"], "Found a duplicate in the metrics slice: aws.neuron.neuroncore.status")
						validatedMetrics["aws.neuron.neuroncore.status"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "sysfs per-NeuronCore status/error counters (runtime-gated; usually zero).", mi.Description())
						assert.Equal(t, "{event}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["aws.neuron.neuroncore.status"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("aws.neuron.neuroncore.id")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("aws.neuron.neuroncore.status")
						assert.False(t, ok)
					}
				case "aws.neuron.neuroncore.time_in_use":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.neuroncore.time_in_use"], "Found a duplicate in the metrics slice: aws.neuron.neuroncore.time_in_use")
						validatedMetrics["aws.neuron.neuroncore.time_in_use"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "NeuronCore time-in-use counter from sysfs (runtime-gated; usually zero).", mi.Description())
						assert.Equal(t, "s", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						neuroncoreAttrVal, ok := dp.Attributes().Get("aws.neuron.neuroncore.id")
						assert.True(t, ok)
						assert.EqualValues(t, 10, neuroncoreAttrVal.Int())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.neuroncore.time_in_use"], "Found a duplicate in the metrics slice: aws.neuron.neuroncore.time_in_use")
						validatedMetrics["aws.neuron.neuroncore.time_in_use"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "NeuronCore time-in-use counter from sysfs (runtime-gated; usually zero).", mi.Description())
						assert.Equal(t, "s", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["aws.neuron.neuroncore.time_in_use"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("aws.neuron.neuroncore.id")
						assert.False(t, ok)
					}
				case "aws.neuron.neuroncore.utilization":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.neuroncore.utilization"], "Found a duplicate in the metrics slice: aws.neuron.neuroncore.utilization")
						validatedMetrics["aws.neuron.neuroncore.utilization"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Fraction of time the NeuronCore was in use.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						neuroncoreAttrVal, ok := dp.Attributes().Get("aws.neuron.neuroncore.id")
						assert.True(t, ok)
						assert.EqualValues(t, 10, neuroncoreAttrVal.Int())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.neuroncore.utilization"], "Found a duplicate in the metrics slice: aws.neuron.neuroncore.utilization")
						validatedMetrics["aws.neuron.neuroncore.utilization"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Fraction of time the NeuronCore was in use.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["aws.neuron.neuroncore.utilization"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("aws.neuron.neuroncore.id")
						assert.False(t, ok)
					}
				case "aws.neuron.runtime.memory.usage":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.runtime.memory.usage"], "Found a duplicate in the metrics slice: aws.neuron.runtime.memory.usage")
						validatedMetrics["aws.neuron.runtime.memory.usage"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Memory used by the Neuron runtime.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.False(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						memoryTypeAttrVal, ok := dp.Attributes().Get("aws.neuron.memory.type")
						assert.True(t, ok)
						assert.Equal(t, "memory_type-val", memoryTypeAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.runtime.memory.usage"], "Found a duplicate in the metrics slice: aws.neuron.runtime.memory.usage")
						validatedMetrics["aws.neuron.runtime.memory.usage"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Memory used by the Neuron runtime.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.False(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["aws.neuron.runtime.memory.usage"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("aws.neuron.memory.type")
						assert.False(t, ok)
					}
				case "aws.neuron.runtime.vcpu.utilization":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.runtime.vcpu.utilization"], "Found a duplicate in the metrics slice: aws.neuron.runtime.vcpu.utilization")
						validatedMetrics["aws.neuron.runtime.vcpu.utilization"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Per-runtime vCPU utilization reported by neuron-monitor.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						cpuStateAttrVal, ok := dp.Attributes().Get("aws.neuron.cpu.state")
						assert.True(t, ok)
						assert.Equal(t, "cpu_state-val", cpuStateAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.runtime.vcpu.utilization"], "Found a duplicate in the metrics slice: aws.neuron.runtime.vcpu.utilization")
						validatedMetrics["aws.neuron.runtime.vcpu.utilization"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Per-runtime vCPU utilization reported by neuron-monitor.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["aws.neuron.runtime.vcpu.utilization"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("aws.neuron.cpu.state")
						assert.False(t, ok)
					}
				case "aws.neuron.system.cpu.utilization":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.system.cpu.utilization"], "Found a duplicate in the metrics slice: aws.neuron.system.cpu.utilization")
						validatedMetrics["aws.neuron.system.cpu.utilization"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "System vCPU utilization reported by neuron-monitor (duplicates the hostmetrics receiver).", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						cpuAttrVal, ok := dp.Attributes().Get("aws.neuron.cpu.logical_number")
						assert.True(t, ok)
						assert.Equal(t, "cpu-val", cpuAttrVal.Str())
						cpuStateAttrVal, ok := dp.Attributes().Get("aws.neuron.cpu.state")
						assert.True(t, ok)
						assert.Equal(t, "cpu_state-val", cpuStateAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.system.cpu.utilization"], "Found a duplicate in the metrics slice: aws.neuron.system.cpu.utilization")
						validatedMetrics["aws.neuron.system.cpu.utilization"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "System vCPU utilization reported by neuron-monitor (duplicates the hostmetrics receiver).", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["aws.neuron.system.cpu.utilization"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("aws.neuron.cpu.logical_number")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("aws.neuron.cpu.state")
						assert.False(t, ok)
					}
				case "aws.neuron.system.memory.usage":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["aws.neuron.system.memory.usage"], "Found a duplicate in the metrics slice: aws.neuron.system.memory.usage")
						validatedMetrics["aws.neuron.system.memory.usage"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "System memory reported by neuron-monitor (duplicates the hostmetrics receiver).", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.False(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						memoryTypeAttrVal, ok := dp.Attributes().Get("aws.neuron.memory.type")
						assert.True(t, ok)
						assert.Equal(t, "memory_type-val", memoryTypeAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["aws.neuron.system.memory.usage"], "Found a duplicate in the metrics slice: aws.neuron.system.memory.usage")
						validatedMetrics["aws.neuron.system.memory.usage"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "System memory reported by neuron-monitor (duplicates the hostmetrics receiver).", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.False(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["aws.neuron.system.memory.usage"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("aws.neuron.memory.type")
						assert.False(t, ok)
					}
				}
			}
		})
	}
}
