// Code generated by github.com/observiq/stix-go/cmd/codegen. DO NOT EDIT.
// Source: STIX 2.1 JSON schemas (cti-stix2-json-schemas).

package stix

// ExternalReference represents a STIX ExternalReference object.
type ExternalReference struct {
	Description string            `json:"description,omitempty"`
	Hashes      map[string]string `json:"hashes,omitempty"`
	Url         string            `json:"url,omitempty"`
}

// GranularMarking represents a STIX GranularMarking object.
type GranularMarking struct {
	Lang       string   `json:"lang,omitempty"`
	MarkingRef string   `json:"marking_ref"`
	Selectors  []string `json:"selectors"`
}

// KillChainPhase represents a STIX KillChainPhase object.
type KillChainPhase struct {
	KillChainName string `json:"kill_chain_name"`
	PhaseName     string `json:"phase_name"`
}

// Extension represents a STIX Extension object.
type Extension struct {
	ExtensionType interface{} `json:"extension_type"`
}

// MarkingDefinition represents a STIX MarkingDefinition object.
type MarkingDefinition struct {
	Created            string                 `json:"created,omitempty"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Name               string                 `json:"name,omitempty"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	SpecVersion        string                 `json:"spec_version,omitempty"`
	Type               string                 `json:"type,omitempty"`
}

// LanguageContent represents a STIX LanguageContent object.
type LanguageContent struct {
	Confidence         int64                  `json:"confidence,omitempty"`
	Contents           map[string]interface{} `json:"contents"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	Modified           string                 `json:"modified"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	ObjectModified     string                 `json:"object_modified,omitempty"`
	ObjectRef          string                 `json:"object_ref"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SpecVersion        string                 `json:"spec_version"`
	Type               string                 `json:"type"`
}

// ExtensionDefinition represents a STIX ExtensionDefinition object.
type ExtensionDefinition struct {
	Confidence          int64                  `json:"confidence,omitempty"`
	Created             string                 `json:"created"`
	CreatedByRef        string                 `json:"created_by_ref,omitempty"`
	Description         string                 `json:"description,omitempty"`
	ExtensionProperties []string               `json:"extension_properties,omitempty"`
	ExtensionTypes      []interface{}          `json:"extension_types"`
	Extensions          map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences  []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings    []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                  interface{}            `json:"id"`
	Labels              []string               `json:"labels,omitempty"`
	Lang                string                 `json:"lang,omitempty"`
	Modified            string                 `json:"modified"`
	Name                string                 `json:"name"`
	ObjectMarkingRefs   []string               `json:"object_marking_refs,omitempty"`
	Revoked             bool                   `json:"revoked,omitempty"`
	Schema              string                 `json:"schema"`
	SpecVersion         string                 `json:"spec_version"`
	Type                string                 `json:"type"`
	Version             string                 `json:"version"`
}

// Core represents a STIX Core object.
type Core struct {
	Confidence         int64                  `json:"confidence,omitempty"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 string                 `json:"id"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	Modified           string                 `json:"modified"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SpecVersion        string                 `json:"spec_version"`
	Type               string                 `json:"type"`
}

// CyberObservableCore represents a STIX CyberObservableCore object.
type CyberObservableCore struct {
	Defanged          bool                   `json:"defanged,omitempty"`
	Extensions        map[string]interface{} `json:"extensions,omitempty"`
	GranularMarkings  []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                string                 `json:"id"`
	ObjectMarkingRefs []string               `json:"object_marking_refs,omitempty"`
	SpecVersion       string                 `json:"spec_version,omitempty"`
	Type              string                 `json:"type"`
}

// Bundle represents a STIX Bundle object.
type Bundle struct {
	Id      string        `json:"id"`
	Objects []interface{} `json:"objects,omitempty"`
	Type    string        `json:"type"`
}

// NetworkTraffic represents a STIX NetworkTraffic object.
type NetworkTraffic struct {
	Defanged          bool                   `json:"defanged,omitempty"`
	DstByteCount      int64                  `json:"dst_byte_count,omitempty"`
	DstPackets        int64                  `json:"dst_packets,omitempty"`
	DstPayloadRef     string                 `json:"dst_payload_ref,omitempty"`
	DstPort           int64                  `json:"dst_port,omitempty"`
	DstRef            string                 `json:"dst_ref,omitempty"`
	EncapsulatedByRef string                 `json:"encapsulated_by_ref,omitempty"`
	EncapsulatesRefs  []string               `json:"encapsulates_refs,omitempty"`
	End               string                 `json:"end,omitempty"`
	Extensions        interface{}            `json:"extensions,omitempty"`
	GranularMarkings  []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                interface{}            `json:"id"`
	Ipfix             map[string]interface{} `json:"ipfix,omitempty"`
	ObjectMarkingRefs []string               `json:"object_marking_refs,omitempty"`
	Protocols         []string               `json:"protocols"`
	SpecVersion       string                 `json:"spec_version,omitempty"`
	SrcByteCount      int64                  `json:"src_byte_count,omitempty"`
	SrcPackets        int64                  `json:"src_packets,omitempty"`
	SrcPayloadRef     string                 `json:"src_payload_ref,omitempty"`
	SrcPort           int64                  `json:"src_port,omitempty"`
	SrcRef            string                 `json:"src_ref,omitempty"`
	Start             string                 `json:"start,omitempty"`
	Type              string                 `json:"type"`
}

// Software represents a STIX Software object.
type Software struct {
	Cpe               string                 `json:"cpe,omitempty"`
	Defanged          bool                   `json:"defanged,omitempty"`
	Extensions        map[string]interface{} `json:"extensions,omitempty"`
	GranularMarkings  []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                interface{}            `json:"id"`
	Languages         []string               `json:"languages,omitempty"`
	Name              string                 `json:"name"`
	ObjectMarkingRefs []string               `json:"object_marking_refs,omitempty"`
	SpecVersion       string                 `json:"spec_version,omitempty"`
	Swid              string                 `json:"swid,omitempty"`
	Type              string                 `json:"type"`
	Vendor            string                 `json:"vendor,omitempty"`
	Version           string                 `json:"version,omitempty"`
}

// UserAccount represents a STIX UserAccount object.
type UserAccount struct {
	AccountCreated        string             `json:"account_created,omitempty"`
	AccountExpires        string             `json:"account_expires,omitempty"`
	AccountFirstLogin     string             `json:"account_first_login,omitempty"`
	AccountLastLogin      string             `json:"account_last_login,omitempty"`
	AccountLogin          string             `json:"account_login,omitempty"`
	AccountType           string             `json:"account_type,omitempty"`
	CanEscalatePrivs      bool               `json:"can_escalate_privs,omitempty"`
	Credential            string             `json:"credential,omitempty"`
	CredentialLastChanged string             `json:"credential_last_changed,omitempty"`
	Defanged              bool               `json:"defanged,omitempty"`
	DisplayName           string             `json:"display_name,omitempty"`
	Extensions            interface{}        `json:"extensions,omitempty"`
	GranularMarkings      []*GranularMarking `json:"granular_markings,omitempty"`
	Id                    interface{}        `json:"id"`
	IsDisabled            bool               `json:"is_disabled,omitempty"`
	IsPrivileged          bool               `json:"is_privileged,omitempty"`
	IsServiceAccount      bool               `json:"is_service_account,omitempty"`
	ObjectMarkingRefs     []string           `json:"object_marking_refs,omitempty"`
	SpecVersion           string             `json:"spec_version,omitempty"`
	Type                  string             `json:"type"`
	UserId                string             `json:"user_id,omitempty"`
}

// Location represents a STIX Location object.
type Location struct {
	AdministrativeArea string                 `json:"administrative_area,omitempty"`
	City               string                 `json:"city,omitempty"`
	Confidence         int64                  `json:"confidence,omitempty"`
	Country            string                 `json:"country,omitempty"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Description        string                 `json:"description,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	Latitude           float64                `json:"latitude,omitempty"`
	Longitude          float64                `json:"longitude,omitempty"`
	Modified           string                 `json:"modified"`
	Name               string                 `json:"name,omitempty"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	PostalCode         string                 `json:"postal_code,omitempty"`
	Precision          float64                `json:"precision,omitempty"`
	Region             string                 `json:"region,omitempty"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SpecVersion        string                 `json:"spec_version"`
	StreetAddress      string                 `json:"street_address,omitempty"`
	Type               string                 `json:"type"`
}

// Malware represents a STIX Malware object.
type Malware struct {
	Aliases                   []string               `json:"aliases,omitempty"`
	ArchitectureExecutionEnvs []string               `json:"architecture_execution_envs,omitempty"`
	Capabilities              []string               `json:"capabilities,omitempty"`
	Confidence                int64                  `json:"confidence,omitempty"`
	Created                   string                 `json:"created"`
	CreatedByRef              string                 `json:"created_by_ref,omitempty"`
	Description               string                 `json:"description,omitempty"`
	Extensions                map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences        []*ExternalReference   `json:"external_references,omitempty"`
	FirstSeen                 string                 `json:"first_seen,omitempty"`
	GranularMarkings          []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                        interface{}            `json:"id"`
	ImplementationLanguages   []string               `json:"implementation_languages,omitempty"`
	KillChainPhases           []*KillChainPhase      `json:"kill_chain_phases,omitempty"`
	Labels                    []string               `json:"labels,omitempty"`
	Lang                      string                 `json:"lang,omitempty"`
	LastSeen                  string                 `json:"last_seen,omitempty"`
	MalwareTypes              []string               `json:"malware_types,omitempty"`
	Modified                  string                 `json:"modified"`
	Name                      string                 `json:"name,omitempty"`
	ObjectMarkingRefs         []string               `json:"object_marking_refs,omitempty"`
	OperatingSystemRefs       []string               `json:"operating_system_refs,omitempty"`
	Revoked                   bool                   `json:"revoked,omitempty"`
	SampleRefs                []string               `json:"sample_refs,omitempty"`
	SpecVersion               string                 `json:"spec_version"`
	Type                      string                 `json:"type"`
}

// Directory represents a STIX Directory object.
type Directory struct {
	Atime             string                 `json:"atime,omitempty"`
	ContainsRefs      []string               `json:"contains_refs,omitempty"`
	Ctime             string                 `json:"ctime,omitempty"`
	Defanged          bool                   `json:"defanged,omitempty"`
	Extensions        map[string]interface{} `json:"extensions,omitempty"`
	GranularMarkings  []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                interface{}            `json:"id"`
	Mtime             string                 `json:"mtime,omitempty"`
	ObjectMarkingRefs []string               `json:"object_marking_refs,omitempty"`
	Path              string                 `json:"path"`
	PathEnc           string                 `json:"path_enc,omitempty"`
	SpecVersion       string                 `json:"spec_version,omitempty"`
	Type              string                 `json:"type"`
}

// Campaign represents a STIX Campaign object.
type Campaign struct {
	Aliases            []string               `json:"aliases,omitempty"`
	Confidence         int64                  `json:"confidence,omitempty"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Description        string                 `json:"description,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	FirstSeen          string                 `json:"first_seen,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	LastSeen           string                 `json:"last_seen,omitempty"`
	Modified           string                 `json:"modified"`
	Name               string                 `json:"name"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	Objective          string                 `json:"objective,omitempty"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SpecVersion        string                 `json:"spec_version"`
	Type               string                 `json:"type"`
}

// Identity represents a STIX Identity object.
type Identity struct {
	Confidence         int64                  `json:"confidence,omitempty"`
	ContactInformation string                 `json:"contact_information,omitempty"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Description        string                 `json:"description,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	IdentityClass      string                 `json:"identity_class,omitempty"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	Modified           string                 `json:"modified"`
	Name               string                 `json:"name"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	Revoked            bool                   `json:"revoked,omitempty"`
	Roles              []string               `json:"roles,omitempty"`
	Sectors            []string               `json:"sectors,omitempty"`
	SpecVersion        string                 `json:"spec_version"`
	Type               string                 `json:"type"`
}

// Tool represents a STIX Tool object.
type Tool struct {
	Aliases            []string               `json:"aliases,omitempty"`
	Confidence         int64                  `json:"confidence,omitempty"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Description        string                 `json:"description,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	KillChainPhases    []*KillChainPhase      `json:"kill_chain_phases,omitempty"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	Modified           string                 `json:"modified"`
	Name               string                 `json:"name"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SpecVersion        string                 `json:"spec_version"`
	ToolTypes          []string               `json:"tool_types,omitempty"`
	ToolVersion        string                 `json:"tool_version,omitempty"`
	Type               string                 `json:"type"`
}

// Infrastructure represents a STIX Infrastructure object.
type Infrastructure struct {
	Aliases             []string               `json:"aliases,omitempty"`
	Confidence          int64                  `json:"confidence,omitempty"`
	Created             string                 `json:"created"`
	CreatedByRef        string                 `json:"created_by_ref,omitempty"`
	Description         string                 `json:"description,omitempty"`
	Extensions          map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences  []*ExternalReference   `json:"external_references,omitempty"`
	FirstSeen           string                 `json:"first_seen,omitempty"`
	GranularMarkings    []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                  interface{}            `json:"id"`
	InfrastructureTypes []string               `json:"infrastructure_types,omitempty"`
	KillChainPhases     []*KillChainPhase      `json:"kill_chain_phases,omitempty"`
	Labels              []string               `json:"labels,omitempty"`
	Lang                string                 `json:"lang,omitempty"`
	LastSeen            string                 `json:"last_seen,omitempty"`
	Modified            string                 `json:"modified"`
	Name                string                 `json:"name"`
	ObjectMarkingRefs   []string               `json:"object_marking_refs,omitempty"`
	Revoked             bool                   `json:"revoked,omitempty"`
	SpecVersion         string                 `json:"spec_version"`
	Type                string                 `json:"type"`
}

// Opinion represents a STIX Opinion object.
type Opinion struct {
	Authors            []string               `json:"authors,omitempty"`
	Confidence         int64                  `json:"confidence,omitempty"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Explanation        string                 `json:"explanation,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	Modified           string                 `json:"modified"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	ObjectRefs         []string               `json:"object_refs"`
	Opinion            string                 `json:"opinion"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SpecVersion        string                 `json:"spec_version"`
	Type               string                 `json:"type"`
}

// CourseOfAction represents a STIX CourseOfAction object.
type CourseOfAction struct {
	Confidence         int64                  `json:"confidence,omitempty"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Description        string                 `json:"description,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	Modified           string                 `json:"modified"`
	Name               string                 `json:"name"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SpecVersion        string                 `json:"spec_version"`
	Type               string                 `json:"type"`
}

// ObservedData represents a STIX ObservedData object.
type ObservedData struct {
	Confidence         int64                  `json:"confidence,omitempty"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	FirstObserved      string                 `json:"first_observed"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	LastObserved       string                 `json:"last_observed"`
	Modified           string                 `json:"modified"`
	NumberObserved     int64                  `json:"number_observed"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	ObjectRefs         []string               `json:"object_refs,omitempty"`
	Objects            map[string]interface{} `json:"objects,omitempty"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SpecVersion        string                 `json:"spec_version"`
	Type               string                 `json:"type"`
}

// Ipv6Addr represents a STIX Ipv6Addr object.
type Ipv6Addr struct {
	BelongsToRefs     []string               `json:"belongs_to_refs,omitempty"`
	Defanged          bool                   `json:"defanged,omitempty"`
	Extensions        map[string]interface{} `json:"extensions,omitempty"`
	GranularMarkings  []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                interface{}            `json:"id"`
	ObjectMarkingRefs []string               `json:"object_marking_refs,omitempty"`
	ResolvesToRefs    []string               `json:"resolves_to_refs,omitempty"`
	SpecVersion       string                 `json:"spec_version,omitempty"`
	Type              string                 `json:"type"`
	Value             string                 `json:"value"`
}

// MacAddr represents a STIX MacAddr object.
type MacAddr struct {
	Defanged          bool                   `json:"defanged,omitempty"`
	Extensions        map[string]interface{} `json:"extensions,omitempty"`
	GranularMarkings  []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                interface{}            `json:"id"`
	ObjectMarkingRefs []string               `json:"object_marking_refs,omitempty"`
	SpecVersion       string                 `json:"spec_version,omitempty"`
	Type              string                 `json:"type"`
	Value             string                 `json:"value"`
}

// Report represents a STIX Report object.
type Report struct {
	Confidence         int64                  `json:"confidence,omitempty"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Description        string                 `json:"description,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	Modified           string                 `json:"modified"`
	Name               string                 `json:"name"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	ObjectRefs         []string               `json:"object_refs"`
	Published          string                 `json:"published"`
	ReportTypes        []string               `json:"report_types,omitempty"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SpecVersion        string                 `json:"spec_version"`
	Type               string                 `json:"type"`
}

// DomainName represents a STIX DomainName object.
type DomainName struct {
	Defanged          bool                   `json:"defanged,omitempty"`
	Extensions        map[string]interface{} `json:"extensions,omitempty"`
	GranularMarkings  []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                interface{}            `json:"id"`
	ObjectMarkingRefs []string               `json:"object_marking_refs,omitempty"`
	ResolvesToRefs    []string               `json:"resolves_to_refs,omitempty"`
	SpecVersion       string                 `json:"spec_version,omitempty"`
	Type              string                 `json:"type"`
	Value             string                 `json:"value"`
}

// Mutex represents a STIX Mutex object.
type Mutex struct {
	Defanged          bool                   `json:"defanged,omitempty"`
	Extensions        map[string]interface{} `json:"extensions,omitempty"`
	GranularMarkings  []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                interface{}            `json:"id"`
	Name              string                 `json:"name"`
	ObjectMarkingRefs []string               `json:"object_marking_refs,omitempty"`
	SpecVersion       string                 `json:"spec_version,omitempty"`
	Type              string                 `json:"type"`
}

// WindowsRegistryKey represents a STIX WindowsRegistryKey object.
type WindowsRegistryKey struct {
	CreatorUserRef    string                 `json:"creator_user_ref,omitempty"`
	Defanged          bool                   `json:"defanged,omitempty"`
	Extensions        map[string]interface{} `json:"extensions,omitempty"`
	GranularMarkings  []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                interface{}            `json:"id"`
	Key               string                 `json:"key,omitempty"`
	ModifiedTime      string                 `json:"modified_time,omitempty"`
	NumberOfSubkeys   int64                  `json:"number_of_subkeys,omitempty"`
	ObjectMarkingRefs []string               `json:"object_marking_refs,omitempty"`
	SpecVersion       string                 `json:"spec_version,omitempty"`
	Type              string                 `json:"type"`
	Values            []interface{}          `json:"values,omitempty"`
}

// Note represents a STIX Note object.
type Note struct {
	Abstract           string                 `json:"abstract,omitempty"`
	Authors            []string               `json:"authors,omitempty"`
	Confidence         int64                  `json:"confidence,omitempty"`
	Content            string                 `json:"content"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	Modified           string                 `json:"modified"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	ObjectRefs         []string               `json:"object_refs"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SpecVersion        string                 `json:"spec_version"`
	Type               string                 `json:"type"`
}

// Sighting represents a STIX Sighting object.
type Sighting struct {
	Confidence         int64                  `json:"confidence,omitempty"`
	Count              int64                  `json:"count,omitempty"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Description        string                 `json:"description,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	FirstSeen          string                 `json:"first_seen,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	LastSeen           string                 `json:"last_seen,omitempty"`
	Modified           string                 `json:"modified"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	ObservedDataRefs   []string               `json:"observed_data_refs,omitempty"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SightingOfRef      string                 `json:"sighting_of_ref"`
	SpecVersion        string                 `json:"spec_version"`
	Summary            bool                   `json:"summary,omitempty"`
	Type               string                 `json:"type"`
	WhereSightedRefs   []string               `json:"where_sighted_refs,omitempty"`
}

// AutonomousSystem represents a STIX AutonomousSystem object.
type AutonomousSystem struct {
	Defanged          bool                   `json:"defanged,omitempty"`
	Extensions        map[string]interface{} `json:"extensions,omitempty"`
	GranularMarkings  []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                interface{}            `json:"id"`
	Name              string                 `json:"name,omitempty"`
	Number            int64                  `json:"number"`
	ObjectMarkingRefs []string               `json:"object_marking_refs,omitempty"`
	Rir               string                 `json:"rir,omitempty"`
	SpecVersion       string                 `json:"spec_version,omitempty"`
	Type              string                 `json:"type"`
}

// File represents a STIX File object.
type File struct {
	Atime              string             `json:"atime,omitempty"`
	ContainsRefs       []string           `json:"contains_refs,omitempty"`
	ContentRef         string             `json:"content_ref,omitempty"`
	Ctime              string             `json:"ctime,omitempty"`
	Defanged           bool               `json:"defanged,omitempty"`
	Extensions         interface{}        `json:"extensions,omitempty"`
	GranularMarkings   []*GranularMarking `json:"granular_markings,omitempty"`
	Hashes             map[string]string  `json:"hashes,omitempty"`
	Id                 interface{}        `json:"id"`
	MagicNumberHex     string             `json:"magic_number_hex,omitempty"`
	MimeType           string             `json:"mime_type,omitempty"`
	Mtime              string             `json:"mtime,omitempty"`
	Name               string             `json:"name,omitempty"`
	NameEnc            string             `json:"name_enc,omitempty"`
	ObjectMarkingRefs  []string           `json:"object_marking_refs,omitempty"`
	ParentDirectoryRef string             `json:"parent_directory_ref,omitempty"`
	Size               int64              `json:"size,omitempty"`
	SpecVersion        string             `json:"spec_version,omitempty"`
	Type               string             `json:"type"`
}

// ThreatActor represents a STIX ThreatActor object.
type ThreatActor struct {
	Aliases              []string               `json:"aliases,omitempty"`
	Confidence           int64                  `json:"confidence,omitempty"`
	Created              string                 `json:"created"`
	CreatedByRef         string                 `json:"created_by_ref,omitempty"`
	Description          string                 `json:"description,omitempty"`
	Extensions           map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences   []*ExternalReference   `json:"external_references,omitempty"`
	FirstSeen            string                 `json:"first_seen,omitempty"`
	Goals                []string               `json:"goals,omitempty"`
	GranularMarkings     []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                   interface{}            `json:"id"`
	Labels               []string               `json:"labels,omitempty"`
	Lang                 string                 `json:"lang,omitempty"`
	LastSeen             string                 `json:"last_seen,omitempty"`
	Modified             string                 `json:"modified"`
	Name                 string                 `json:"name"`
	ObjectMarkingRefs    []string               `json:"object_marking_refs,omitempty"`
	PersonalMotivations  []string               `json:"personal_motivations,omitempty"`
	PrimaryMotivation    string                 `json:"primary_motivation,omitempty"`
	ResourceLevel        string                 `json:"resource_level,omitempty"`
	Revoked              bool                   `json:"revoked,omitempty"`
	Roles                []string               `json:"roles,omitempty"`
	SecondaryMotivations []string               `json:"secondary_motivations,omitempty"`
	Sophistication       string                 `json:"sophistication,omitempty"`
	SpecVersion          string                 `json:"spec_version"`
	ThreatActorTypes     []string               `json:"threat_actor_types,omitempty"`
	Type                 string                 `json:"type"`
}

// Relationship represents a STIX Relationship object.
type Relationship struct {
	Confidence         int64                  `json:"confidence,omitempty"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Description        string                 `json:"description,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	Modified           string                 `json:"modified"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	RelationshipType   string                 `json:"relationship_type"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SourceRef          string                 `json:"source_ref"`
	SpecVersion        string                 `json:"spec_version"`
	StartTime          string                 `json:"start_time,omitempty"`
	StopTime           string                 `json:"stop_time,omitempty"`
	TargetRef          string                 `json:"target_ref"`
	Type               string                 `json:"type"`
}

// EmailMessage represents a STIX EmailMessage object.
type EmailMessage struct {
	AdditionalHeaderFields interface{}            `json:"additional_header_fields,omitempty"`
	BccRefs                []string               `json:"bcc_refs,omitempty"`
	CcRefs                 []string               `json:"cc_refs,omitempty"`
	ContentType            string                 `json:"content_type,omitempty"`
	Date                   string                 `json:"date,omitempty"`
	Defanged               bool                   `json:"defanged,omitempty"`
	Extensions             map[string]interface{} `json:"extensions,omitempty"`
	FromRef                string                 `json:"from_ref,omitempty"`
	GranularMarkings       []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                     interface{}            `json:"id"`
	MessageId              string                 `json:"message_id,omitempty"`
	ObjectMarkingRefs      []string               `json:"object_marking_refs,omitempty"`
	RawEmailRef            string                 `json:"raw_email_ref,omitempty"`
	ReceivedLines          []string               `json:"received_lines,omitempty"`
	SenderRef              string                 `json:"sender_ref,omitempty"`
	SpecVersion            string                 `json:"spec_version,omitempty"`
	Subject                string                 `json:"subject,omitempty"`
	ToRefs                 []string               `json:"to_refs,omitempty"`
	Type                   string                 `json:"type"`
}

// Ipv4Addr represents a STIX Ipv4Addr object.
type Ipv4Addr struct {
	BelongsToRefs     []string               `json:"belongs_to_refs,omitempty"`
	Defanged          bool                   `json:"defanged,omitempty"`
	Extensions        map[string]interface{} `json:"extensions,omitempty"`
	GranularMarkings  []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                interface{}            `json:"id"`
	ObjectMarkingRefs []string               `json:"object_marking_refs,omitempty"`
	ResolvesToRefs    []string               `json:"resolves_to_refs,omitempty"`
	SpecVersion       string                 `json:"spec_version,omitempty"`
	Type              string                 `json:"type"`
	Value             string                 `json:"value"`
}

// Process represents a STIX Process object.
type Process struct {
	ChildRefs            []string               `json:"child_refs,omitempty"`
	CommandLine          string                 `json:"command_line,omitempty"`
	CreatedTime          string                 `json:"created_time,omitempty"`
	CreatorUserRef       string                 `json:"creator_user_ref,omitempty"`
	Cwd                  string                 `json:"cwd,omitempty"`
	Defanged             bool                   `json:"defanged,omitempty"`
	EnvironmentVariables map[string]interface{} `json:"environment_variables,omitempty"`
	Extensions           interface{}            `json:"extensions,omitempty"`
	GranularMarkings     []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                   interface{}            `json:"id"`
	ImageRef             string                 `json:"image_ref,omitempty"`
	IsHidden             bool                   `json:"is_hidden,omitempty"`
	ObjectMarkingRefs    []string               `json:"object_marking_refs,omitempty"`
	OpenedConnectionRefs []string               `json:"opened_connection_refs,omitempty"`
	ParentRef            string                 `json:"parent_ref,omitempty"`
	Pid                  int64                  `json:"pid,omitempty"`
	SpecVersion          string                 `json:"spec_version,omitempty"`
	Type                 string                 `json:"type"`
}

// AttackPattern represents a STIX AttackPattern object.
type AttackPattern struct {
	Aliases            []string               `json:"aliases,omitempty"`
	Confidence         int64                  `json:"confidence,omitempty"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Description        string                 `json:"description,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	KillChainPhases    []*KillChainPhase      `json:"kill_chain_phases,omitempty"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	Modified           string                 `json:"modified"`
	Name               string                 `json:"name"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SpecVersion        string                 `json:"spec_version"`
	Type               string                 `json:"type"`
}

// IntrusionSet represents a STIX IntrusionSet object.
type IntrusionSet struct {
	Aliases              []string               `json:"aliases,omitempty"`
	Confidence           int64                  `json:"confidence,omitempty"`
	Created              string                 `json:"created"`
	CreatedByRef         string                 `json:"created_by_ref,omitempty"`
	Description          string                 `json:"description,omitempty"`
	Extensions           map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences   []*ExternalReference   `json:"external_references,omitempty"`
	FirstSeen            string                 `json:"first_seen,omitempty"`
	Goals                []string               `json:"goals,omitempty"`
	GranularMarkings     []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                   interface{}            `json:"id"`
	Labels               []string               `json:"labels,omitempty"`
	Lang                 string                 `json:"lang,omitempty"`
	LastSeen             string                 `json:"last_seen,omitempty"`
	Modified             string                 `json:"modified"`
	Name                 string                 `json:"name"`
	ObjectMarkingRefs    []string               `json:"object_marking_refs,omitempty"`
	PrimaryMotivation    string                 `json:"primary_motivation,omitempty"`
	ResourceLevel        string                 `json:"resource_level,omitempty"`
	Revoked              bool                   `json:"revoked,omitempty"`
	SecondaryMotivations []string               `json:"secondary_motivations,omitempty"`
	SpecVersion          string                 `json:"spec_version"`
	Type                 string                 `json:"type"`
}

// Artifact represents a STIX Artifact object.
type Artifact struct {
	DecryptionKey       string                 `json:"decryption_key,omitempty"`
	Defanged            bool                   `json:"defanged,omitempty"`
	EncryptionAlgorithm interface{}            `json:"encryption_algorithm,omitempty"`
	Extensions          map[string]interface{} `json:"extensions,omitempty"`
	GranularMarkings    []*GranularMarking     `json:"granular_markings,omitempty"`
	Hashes              map[string]string      `json:"hashes,omitempty"`
	Id                  interface{}            `json:"id"`
	MimeType            string                 `json:"mime_type,omitempty"`
	ObjectMarkingRefs   []string               `json:"object_marking_refs,omitempty"`
	PayloadBin          []byte                 `json:"payload_bin,omitempty"`
	SpecVersion         string                 `json:"spec_version,omitempty"`
	Type                string                 `json:"type"`
	Url                 string                 `json:"url,omitempty"`
}

// Indicator represents a STIX Indicator object.
type Indicator struct {
	Confidence         int64                  `json:"confidence,omitempty"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Description        string                 `json:"description,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	IndicatorTypes     []string               `json:"indicator_types,omitempty"`
	KillChainPhases    []*KillChainPhase      `json:"kill_chain_phases,omitempty"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	Modified           string                 `json:"modified"`
	Name               string                 `json:"name,omitempty"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	Pattern            string                 `json:"pattern"`
	PatternType        string                 `json:"pattern_type"`
	PatternVersion     string                 `json:"pattern_version,omitempty"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SpecVersion        string                 `json:"spec_version"`
	Type               string                 `json:"type"`
	ValidFrom          string                 `json:"valid_from"`
	ValidUntil         string                 `json:"valid_until,omitempty"`
}

// Url represents a STIX Url object.
type Url struct {
	Defanged          bool                   `json:"defanged,omitempty"`
	Extensions        map[string]interface{} `json:"extensions,omitempty"`
	GranularMarkings  []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                interface{}            `json:"id"`
	ObjectMarkingRefs []string               `json:"object_marking_refs,omitempty"`
	SpecVersion       string                 `json:"spec_version,omitempty"`
	Type              string                 `json:"type"`
	Value             string                 `json:"value"`
}

// Vulnerability represents a STIX Vulnerability object.
type Vulnerability struct {
	Confidence         int64                  `json:"confidence,omitempty"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Description        string                 `json:"description,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	Modified           string                 `json:"modified"`
	Name               string                 `json:"name"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SpecVersion        string                 `json:"spec_version"`
	Type               string                 `json:"type"`
}

// Grouping represents a STIX Grouping object.
type Grouping struct {
	Confidence         int64                  `json:"confidence,omitempty"`
	Context            string                 `json:"context"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Description        string                 `json:"description,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	Modified           string                 `json:"modified"`
	Name               string                 `json:"name,omitempty"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	ObjectRefs         []string               `json:"object_refs"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SpecVersion        string                 `json:"spec_version"`
	Type               string                 `json:"type"`
}

// Incident represents a STIX Incident object.
type Incident struct {
	Confidence         int64                  `json:"confidence,omitempty"`
	Created            string                 `json:"created"`
	CreatedByRef       string                 `json:"created_by_ref,omitempty"`
	Description        string                 `json:"description,omitempty"`
	Extensions         map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings   []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                 interface{}            `json:"id"`
	Labels             []string               `json:"labels,omitempty"`
	Lang               string                 `json:"lang,omitempty"`
	Modified           string                 `json:"modified"`
	Name               string                 `json:"name"`
	ObjectMarkingRefs  []string               `json:"object_marking_refs,omitempty"`
	Revoked            bool                   `json:"revoked,omitempty"`
	SpecVersion        string                 `json:"spec_version"`
	Type               string                 `json:"type"`
}

// X509Certificate represents a STIX X509Certificate object.
type X509Certificate struct {
	Defanged                  bool                   `json:"defanged,omitempty"`
	Extensions                map[string]interface{} `json:"extensions,omitempty"`
	GranularMarkings          []*GranularMarking     `json:"granular_markings,omitempty"`
	Hashes                    map[string]string      `json:"hashes,omitempty"`
	Id                        interface{}            `json:"id"`
	IsSelfSigned              bool                   `json:"is_self_signed,omitempty"`
	Issuer                    string                 `json:"issuer,omitempty"`
	ObjectMarkingRefs         []string               `json:"object_marking_refs,omitempty"`
	SerialNumber              string                 `json:"serial_number,omitempty"`
	SignatureAlgorithm        string                 `json:"signature_algorithm,omitempty"`
	SpecVersion               string                 `json:"spec_version,omitempty"`
	Subject                   string                 `json:"subject,omitempty"`
	SubjectPublicKeyAlgorithm string                 `json:"subject_public_key_algorithm,omitempty"`
	SubjectPublicKeyExponent  int64                  `json:"subject_public_key_exponent,omitempty"`
	SubjectPublicKeyModulus   string                 `json:"subject_public_key_modulus,omitempty"`
	Type                      string                 `json:"type"`
	ValidityNotAfter          string                 `json:"validity_not_after,omitempty"`
	ValidityNotBefore         string                 `json:"validity_not_before,omitempty"`
	Version                   string                 `json:"version,omitempty"`
	X509V3Extensions          interface{}            `json:"x509_v3_extensions,omitempty"`
}

// MalwareAnalysis represents a STIX MalwareAnalysis object.
type MalwareAnalysis struct {
	AnalysisDefinitionVersion string                 `json:"analysis_definition_version,omitempty"`
	AnalysisEnded             string                 `json:"analysis_ended,omitempty"`
	AnalysisEngineVersion     string                 `json:"analysis_engine_version,omitempty"`
	AnalysisScoRefs           []string               `json:"analysis_sco_refs,omitempty"`
	AnalysisStarted           string                 `json:"analysis_started,omitempty"`
	Confidence                int64                  `json:"confidence,omitempty"`
	ConfigurationVersion      string                 `json:"configuration_version,omitempty"`
	Created                   string                 `json:"created"`
	CreatedByRef              string                 `json:"created_by_ref,omitempty"`
	Extensions                map[string]interface{} `json:"extensions,omitempty"`
	ExternalReferences        []*ExternalReference   `json:"external_references,omitempty"`
	GranularMarkings          []*GranularMarking     `json:"granular_markings,omitempty"`
	HostVmRef                 string                 `json:"host_vm_ref,omitempty"`
	Id                        interface{}            `json:"id"`
	InstalledSoftwareRefs     []string               `json:"installed_software_refs,omitempty"`
	Labels                    []string               `json:"labels,omitempty"`
	Lang                      string                 `json:"lang,omitempty"`
	Modified                  string                 `json:"modified"`
	Modules                   []string               `json:"modules,omitempty"`
	ObjectMarkingRefs         []string               `json:"object_marking_refs,omitempty"`
	OperatingSystemRef        string                 `json:"operating_system_ref,omitempty"`
	Product                   string                 `json:"product"`
	Result                    string                 `json:"result,omitempty"`
	ResultName                string                 `json:"result_name,omitempty"`
	Revoked                   bool                   `json:"revoked,omitempty"`
	SampleRef                 string                 `json:"sample_ref,omitempty"`
	SpecVersion               string                 `json:"spec_version"`
	Submitted                 string                 `json:"submitted,omitempty"`
	Type                      string                 `json:"type"`
	Version                   string                 `json:"version,omitempty"`
}

// EmailAddr represents a STIX EmailAddr object.
type EmailAddr struct {
	BelongsToRef      string                 `json:"belongs_to_ref,omitempty"`
	Defanged          bool                   `json:"defanged,omitempty"`
	DisplayName       string                 `json:"display_name,omitempty"`
	Extensions        map[string]interface{} `json:"extensions,omitempty"`
	GranularMarkings  []*GranularMarking     `json:"granular_markings,omitempty"`
	Id                interface{}            `json:"id"`
	ObjectMarkingRefs []string               `json:"object_marking_refs,omitempty"`
	SpecVersion       string                 `json:"spec_version,omitempty"`
	Type              string                 `json:"type"`
	Value             string                 `json:"value"`
}
