// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/bindplaneauditlogs component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("bindplaneauditlogs")
	ScopeName = "github.com/observiq/bindplane-otel-contrib/receiver/bindplaneauditlogs"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
