// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("amq")
	ScopeName = "github.com/observiq/bindplane-otel-contrib/extension/amqextension"
)

const (
	ExtensionStability = component.StabilityLevelAlpha
)
