// Request message for importing stats events via the REST importStatsEvents API.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: secops_stats_http.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImportStatsEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*ImportStatsEventsRequest_InlineSource
	Source        isImportStatsEventsRequest_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportStatsEventsRequest) Reset() {
	*x = ImportStatsEventsRequest{}
	mi := &file_secops_stats_http_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportStatsEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportStatsEventsRequest) ProtoMessage() {}

func (x *ImportStatsEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secops_stats_http_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportStatsEventsRequest.ProtoReflect.Descriptor instead.
func (*ImportStatsEventsRequest) Descriptor() ([]byte, []int) {
	return file_secops_stats_http_proto_rawDescGZIP(), []int{0}
}

func (x *ImportStatsEventsRequest) GetSource() isImportStatsEventsRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ImportStatsEventsRequest) GetInlineSource() *StatsInlineSource {
	if x != nil {
		if x, ok := x.Source.(*ImportStatsEventsRequest_InlineSource); ok {
			return x.InlineSource
		}
	}
	return nil
}

type isImportStatsEventsRequest_Source interface {
	isImportStatsEventsRequest_Source()
}

type ImportStatsEventsRequest_InlineSource struct {
	// Stats events to be imported are specified inline.
	InlineSource *StatsInlineSource `protobuf:"bytes,1,opt,name=inline_source,json=inlineSource,proto3,oneof"`
}

func (*ImportStatsEventsRequest_InlineSource) isImportStatsEventsRequest_Source() {}

// An inline source containing stats events.
type StatsInlineSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stats events being imported.
	Events []*IngestionStatsEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// Unique batch ID for deduplication.
	EventBatchId  string `protobuf:"bytes,2,opt,name=event_batch_id,json=eventBatchId,proto3" json:"event_batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsInlineSource) Reset() {
	*x = StatsInlineSource{}
	mi := &file_secops_stats_http_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsInlineSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsInlineSource) ProtoMessage() {}

func (x *StatsInlineSource) ProtoReflect() protoreflect.Message {
	mi := &file_secops_stats_http_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsInlineSource.ProtoReflect.Descriptor instead.
func (*StatsInlineSource) Descriptor() ([]byte, []int) {
	return file_secops_stats_http_proto_rawDescGZIP(), []int{1}
}

func (x *StatsInlineSource) GetEvents() []*IngestionStatsEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *StatsInlineSource) GetEventBatchId() string {
	if x != nil {
		return x.EventBatchId
	}
	return ""
}

// Wrapper for an individual stats event.
type IngestionStatsEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The time at which the event occurred.
	EventTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*IngestionStatsEvent_Stats
	//	*IngestionStatsEvent_AgentStats
	Event         isIngestionStatsEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionStatsEvent) Reset() {
	*x = IngestionStatsEvent{}
	mi := &file_secops_stats_http_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionStatsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionStatsEvent) ProtoMessage() {}

func (x *IngestionStatsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_secops_stats_http_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionStatsEvent.ProtoReflect.Descriptor instead.
func (*IngestionStatsEvent) Descriptor() ([]byte, []int) {
	return file_secops_stats_http_proto_rawDescGZIP(), []int{2}
}

func (x *IngestionStatsEvent) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *IngestionStatsEvent) GetEvent() isIngestionStatsEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *IngestionStatsEvent) GetStats() *StatsEvent {
	if x != nil {
		if x, ok := x.Event.(*IngestionStatsEvent_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

func (x *IngestionStatsEvent) GetAgentStats() *AgentStatsEvent {
	if x != nil {
		if x, ok := x.Event.(*IngestionStatsEvent_AgentStats); ok {
			return x.AgentStats
		}
	}
	return nil
}

type isIngestionStatsEvent_Event interface {
	isIngestionStatsEvent_Event()
}

type IngestionStatsEvent_Stats struct {
	// Native forwarder stats event.
	Stats *StatsEvent `protobuf:"bytes,2,opt,name=stats,proto3,oneof"`
}

type IngestionStatsEvent_AgentStats struct {
	// Collection agent stats event.
	AgentStats *AgentStatsEvent `protobuf:"bytes,3,opt,name=agent_stats,json=agentStats,proto3,oneof"`
}

func (*IngestionStatsEvent_Stats) isIngestionStatsEvent_Event() {}

func (*IngestionStatsEvent_AgentStats) isIngestionStatsEvent_Event() {}

// Native forwarder stats event (not used by this agent).
type StatsEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsEvent) Reset() {
	*x = StatsEvent{}
	mi := &file_secops_stats_http_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsEvent) ProtoMessage() {}

func (x *StatsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_secops_stats_http_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsEvent.ProtoReflect.Descriptor instead.
func (*StatsEvent) Descriptor() ([]byte, []int) {
	return file_secops_stats_http_proto_rawDescGZIP(), []int{3}
}

var File_secops_stats_http_proto protoreflect.FileDescriptor

const file_secops_stats_http_proto_rawDesc = "" +
	"\n" +
	"\x17secops_stats_http.proto\x12\x14googlesecopsexporter\x1a\x12secops_stats.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"t\n" +
	"\x18ImportStatsEventsRequest\x12N\n" +
	"\rinline_source\x18\x01 \x01(\v2'.googlesecopsexporter.StatsInlineSourceH\x00R\finlineSourceB\b\n" +
	"\x06source\"|\n" +
	"\x11StatsInlineSource\x12A\n" +
	"\x06events\x18\x01 \x03(\v2).googlesecopsexporter.IngestionStatsEventR\x06events\x12$\n" +
	"\x0eevent_batch_id\x18\x02 \x01(\tR\feventBatchId\"\xdd\x01\n" +
	"\x13IngestionStatsEvent\x129\n" +
	"\n" +
	"event_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\teventTime\x128\n" +
	"\x05stats\x18\x02 \x01(\v2 .googlesecopsexporter.StatsEventH\x00R\x05stats\x12H\n" +
	"\vagent_stats\x18\x03 \x01(\v2%.googlesecopsexporter.AgentStatsEventH\x00R\n" +
	"agentStatsB\a\n" +
	"\x05event\"\f\n" +
	"\n" +
	"StatsEventB4Z2github.com/exporter/googlesecopsexporter/proto/apib\x06proto3"

var (
	file_secops_stats_http_proto_rawDescOnce sync.Once
	file_secops_stats_http_proto_rawDescData []byte
)

func file_secops_stats_http_proto_rawDescGZIP() []byte {
	file_secops_stats_http_proto_rawDescOnce.Do(func() {
		file_secops_stats_http_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secops_stats_http_proto_rawDesc), len(file_secops_stats_http_proto_rawDesc)))
	})
	return file_secops_stats_http_proto_rawDescData
}

var file_secops_stats_http_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_secops_stats_http_proto_goTypes = []any{
	(*ImportStatsEventsRequest)(nil), // 0: googlesecopsexporter.ImportStatsEventsRequest
	(*StatsInlineSource)(nil),        // 1: googlesecopsexporter.StatsInlineSource
	(*IngestionStatsEvent)(nil),      // 2: googlesecopsexporter.IngestionStatsEvent
	(*StatsEvent)(nil),               // 3: googlesecopsexporter.StatsEvent
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
	(*AgentStatsEvent)(nil),          // 5: googlesecopsexporter.AgentStatsEvent
}
var file_secops_stats_http_proto_depIdxs = []int32{
	1, // 0: googlesecopsexporter.ImportStatsEventsRequest.inline_source:type_name -> googlesecopsexporter.StatsInlineSource
	2, // 1: googlesecopsexporter.StatsInlineSource.events:type_name -> googlesecopsexporter.IngestionStatsEvent
	4, // 2: googlesecopsexporter.IngestionStatsEvent.event_time:type_name -> google.protobuf.Timestamp
	3, // 3: googlesecopsexporter.IngestionStatsEvent.stats:type_name -> googlesecopsexporter.StatsEvent
	5, // 4: googlesecopsexporter.IngestionStatsEvent.agent_stats:type_name -> googlesecopsexporter.AgentStatsEvent
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_secops_stats_http_proto_init() }
func file_secops_stats_http_proto_init() {
	if File_secops_stats_http_proto != nil {
		return
	}
	file_secops_stats_proto_init()
	file_secops_stats_http_proto_msgTypes[0].OneofWrappers = []any{
		(*ImportStatsEventsRequest_InlineSource)(nil),
	}
	file_secops_stats_http_proto_msgTypes[2].OneofWrappers = []any{
		(*IngestionStatsEvent_Stats)(nil),
		(*IngestionStatsEvent_AgentStats)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secops_stats_http_proto_rawDesc), len(file_secops_stats_http_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_secops_stats_http_proto_goTypes,
		DependencyIndexes: file_secops_stats_http_proto_depIdxs,
		MessageInfos:      file_secops_stats_http_proto_msgTypes,
	}.Build()
	File_secops_stats_http_proto = out.File
	file_secops_stats_http_proto_goTypes = nil
	file_secops_stats_http_proto_depIdxs = nil
}
