// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/observiq/bindplane-otel-contrib/processor/logtypedetectionprocessor")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/observiq/bindplane-otel-contrib/processor/logtypedetectionprocessor")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                     metric.Meter
	mu                                        sync.Mutex
	registrations                             []metric.Registration
	ProcessorLogTypeDetectionAttempts         metric.Int64Counter
	ProcessorLogTypeDetectionAttemptsMatched  metric.Int64Counter
	ProcessorLogTypeDetectionLogsClassified   metric.Int64Counter
	ProcessorLogTypeDetectionLogsUnclassified metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ProcessorLogTypeDetectionAttempts, err = builder.meter.Int64Counter(
		"otelcol_processor_log_type_detection_attempts",
		metric.WithDescription("Number of log type detections attempted, one per newly seen log structure. [Alpha]"),
		metric.WithUnit("{detection}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorLogTypeDetectionAttemptsMatched, err = builder.meter.Int64Counter(
		"otelcol_processor_log_type_detection_attempts_matched",
		metric.WithDescription("Number of log type detection attempts that matched, one per newly seen log structure. [Alpha]"),
		metric.WithUnit("{detection}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorLogTypeDetectionLogsClassified, err = builder.meter.Int64Counter(
		"otelcol_processor_log_type_detection_logs_classified",
		metric.WithDescription("Number of log records assigned a log type. [Alpha]"),
		metric.WithUnit("{log}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorLogTypeDetectionLogsUnclassified, err = builder.meter.Int64Counter(
		"otelcol_processor_log_type_detection_logs_unclassified",
		metric.WithDescription("Number of log records with no detected log type. [Alpha]"),
		metric.WithUnit("{log}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
