// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/log_type_detection component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("log_type_detection")
	ScopeName = "github.com/observiq/bindplane-otel-contrib/processor/logtypedetectionprocessor"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
