// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					SapnetweaverAbapUpdateStatus: SapnetweaverAbapUpdateStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverAbapUpdateStatusMetricAttributeKey{SapnetweaverAbapUpdateStatusMetricAttributeKeyControlState},
					},
					SapnetweaverCacheEvictions: SapnetweaverCacheEvictionsMetricConfig{
						Enabled: true,
					},
					SapnetweaverCacheHits: SapnetweaverCacheHitsMetricConfig{
						Enabled: true,
					},
					SapnetweaverConnectionErrorCount: SapnetweaverConnectionErrorCountMetricConfig{
						Enabled: true,
					},
					SapnetweaverCPUSystemUtilization: SapnetweaverCPUSystemUtilizationMetricConfig{
						Enabled: true,
					},
					SapnetweaverCPUUtilization: SapnetweaverCPUUtilizationMetricConfig{
						Enabled: true,
					},
					SapnetweaverDatabaseDialogRequestTime: SapnetweaverDatabaseDialogRequestTimeMetricConfig{
						Enabled: true,
					},
					SapnetweaverHostMemoryVirtualOverhead: SapnetweaverHostMemoryVirtualOverheadMetricConfig{
						Enabled: true,
					},
					SapnetweaverHostMemoryVirtualSwap: SapnetweaverHostMemoryVirtualSwapMetricConfig{
						Enabled: true,
					},
					SapnetweaverHostSpoolListUtilization: SapnetweaverHostSpoolListUtilizationMetricConfig{
						Enabled: true,
					},
					SapnetweaverLocksDequeueErrorsCount: SapnetweaverLocksDequeueErrorsCountMetricConfig{
						Enabled: true,
					},
					SapnetweaverLocksEnqueueCurrentCount: SapnetweaverLocksEnqueueCurrentCountMetricConfig{
						Enabled: true,
					},
					SapnetweaverLocksEnqueueErrorsCount: SapnetweaverLocksEnqueueErrorsCountMetricConfig{
						Enabled: true,
					},
					SapnetweaverLocksEnqueueHighCount: SapnetweaverLocksEnqueueHighCountMetricConfig{
						Enabled: true,
					},
					SapnetweaverLocksEnqueueLockTime: SapnetweaverLocksEnqueueLockTimeMetricConfig{
						Enabled: true,
					},
					SapnetweaverLocksEnqueueLockWaitTime: SapnetweaverLocksEnqueueLockWaitTimeMetricConfig{
						Enabled: true,
					},
					SapnetweaverLocksEnqueueMaxCount: SapnetweaverLocksEnqueueMaxCountMetricConfig{
						Enabled: true,
					},
					SapnetweaverMemoryConfigured: SapnetweaverMemoryConfiguredMetricConfig{
						Enabled: true,
					},
					SapnetweaverMemoryFree: SapnetweaverMemoryFreeMetricConfig{
						Enabled: true,
					},
					SapnetweaverMemorySwapSpaceUtilization: SapnetweaverMemorySwapSpaceUtilizationMetricConfig{
						Enabled: true,
					},
					SapnetweaverProcessAvailability: SapnetweaverProcessAvailabilityMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverProcessAvailabilityMetricAttributeKey{SapnetweaverProcessAvailabilityMetricAttributeKeyProcessName, SapnetweaverProcessAvailabilityMetricAttributeKeyProcessDescription, SapnetweaverProcessAvailabilityMetricAttributeKeyControlState},
					},
					SapnetweaverQueueCount: SapnetweaverQueueCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverQueueCountMetricAttributeKey{SapnetweaverQueueCountMetricAttributeKeyWpType},
					},
					SapnetweaverQueueMaxCount: SapnetweaverQueueMaxCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverQueueMaxCountMetricAttributeKey{SapnetweaverQueueMaxCountMetricAttributeKeyWpType},
					},
					SapnetweaverQueuePeakCount: SapnetweaverQueuePeakCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverQueuePeakCountMetricAttributeKey{SapnetweaverQueuePeakCountMetricAttributeKeyWpType},
					},
					SapnetweaverRequestCount: SapnetweaverRequestCountMetricConfig{
						Enabled: true,
					},
					SapnetweaverRequestTimeoutCount: SapnetweaverRequestTimeoutCountMetricConfig{
						Enabled: true,
					},
					SapnetweaverResponseDuration: SapnetweaverResponseDurationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverResponseDurationMetricAttributeKey{SapnetweaverResponseDurationMetricAttributeKeyResponseType},
					},
					SapnetweaverSessionCount: SapnetweaverSessionCountMetricConfig{
						Enabled: true,
					},
					SapnetweaverSessionsBrowserCount: SapnetweaverSessionsBrowserCountMetricConfig{
						Enabled: true,
					},
					SapnetweaverSessionsEjbCount: SapnetweaverSessionsEjbCountMetricConfig{
						Enabled: true,
					},
					SapnetweaverSessionsHTTPCount: SapnetweaverSessionsHTTPCountMetricConfig{
						Enabled: true,
					},
					SapnetweaverSessionsSecurityCount: SapnetweaverSessionsSecurityCountMetricConfig{
						Enabled: true,
					},
					SapnetweaverSessionsWebCount: SapnetweaverSessionsWebCountMetricConfig{
						Enabled: true,
					},
					SapnetweaverShortDumpsRate: SapnetweaverShortDumpsRateMetricConfig{
						Enabled: true,
					},
					SapnetweaverSpoolRequestErrorCount: SapnetweaverSpoolRequestErrorCountMetricConfig{
						Enabled: true,
					},
					SapnetweaverSystemInstanceAvailability: SapnetweaverSystemInstanceAvailabilityMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverSystemInstanceAvailabilityMetricAttributeKey{SapnetweaverSystemInstanceAvailabilityMetricAttributeKeyHostname, SapnetweaverSystemInstanceAvailabilityMetricAttributeKeyInstanceNumber, SapnetweaverSystemInstanceAvailabilityMetricAttributeKeyFeature, SapnetweaverSystemInstanceAvailabilityMetricAttributeKeyControlState},
					},
					SapnetweaverWorkProcessActiveCount: SapnetweaverWorkProcessActiveCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverWorkProcessActiveCountMetricAttributeKey{SapnetweaverWorkProcessActiveCountMetricAttributeKeyInstance, SapnetweaverWorkProcessActiveCountMetricAttributeKeyWpType, SapnetweaverWorkProcessActiveCountMetricAttributeKeyWpStatus},
					},
					SapnetweaverWorkProcessJobAbortedStatus: SapnetweaverWorkProcessJobAbortedStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverWorkProcessJobAbortedStatusMetricAttributeKey{SapnetweaverWorkProcessJobAbortedStatusMetricAttributeKeyControlState},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					SapnetweaverSID:      ResourceAttributeConfig{Enabled: true},
					SapnetweaverInstance: ResourceAttributeConfig{Enabled: true},
					SapnetweaverNode:     ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					SapnetweaverAbapUpdateStatus: SapnetweaverAbapUpdateStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverAbapUpdateStatusMetricAttributeKey{SapnetweaverAbapUpdateStatusMetricAttributeKeyControlState},
					},
					SapnetweaverCacheEvictions: SapnetweaverCacheEvictionsMetricConfig{
						Enabled: false,
					},
					SapnetweaverCacheHits: SapnetweaverCacheHitsMetricConfig{
						Enabled: false,
					},
					SapnetweaverConnectionErrorCount: SapnetweaverConnectionErrorCountMetricConfig{
						Enabled: false,
					},
					SapnetweaverCPUSystemUtilization: SapnetweaverCPUSystemUtilizationMetricConfig{
						Enabled: false,
					},
					SapnetweaverCPUUtilization: SapnetweaverCPUUtilizationMetricConfig{
						Enabled: false,
					},
					SapnetweaverDatabaseDialogRequestTime: SapnetweaverDatabaseDialogRequestTimeMetricConfig{
						Enabled: false,
					},
					SapnetweaverHostMemoryVirtualOverhead: SapnetweaverHostMemoryVirtualOverheadMetricConfig{
						Enabled: false,
					},
					SapnetweaverHostMemoryVirtualSwap: SapnetweaverHostMemoryVirtualSwapMetricConfig{
						Enabled: false,
					},
					SapnetweaverHostSpoolListUtilization: SapnetweaverHostSpoolListUtilizationMetricConfig{
						Enabled: false,
					},
					SapnetweaverLocksDequeueErrorsCount: SapnetweaverLocksDequeueErrorsCountMetricConfig{
						Enabled: false,
					},
					SapnetweaverLocksEnqueueCurrentCount: SapnetweaverLocksEnqueueCurrentCountMetricConfig{
						Enabled: false,
					},
					SapnetweaverLocksEnqueueErrorsCount: SapnetweaverLocksEnqueueErrorsCountMetricConfig{
						Enabled: false,
					},
					SapnetweaverLocksEnqueueHighCount: SapnetweaverLocksEnqueueHighCountMetricConfig{
						Enabled: false,
					},
					SapnetweaverLocksEnqueueLockTime: SapnetweaverLocksEnqueueLockTimeMetricConfig{
						Enabled: false,
					},
					SapnetweaverLocksEnqueueLockWaitTime: SapnetweaverLocksEnqueueLockWaitTimeMetricConfig{
						Enabled: false,
					},
					SapnetweaverLocksEnqueueMaxCount: SapnetweaverLocksEnqueueMaxCountMetricConfig{
						Enabled: false,
					},
					SapnetweaverMemoryConfigured: SapnetweaverMemoryConfiguredMetricConfig{
						Enabled: false,
					},
					SapnetweaverMemoryFree: SapnetweaverMemoryFreeMetricConfig{
						Enabled: false,
					},
					SapnetweaverMemorySwapSpaceUtilization: SapnetweaverMemorySwapSpaceUtilizationMetricConfig{
						Enabled: false,
					},
					SapnetweaverProcessAvailability: SapnetweaverProcessAvailabilityMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverProcessAvailabilityMetricAttributeKey{SapnetweaverProcessAvailabilityMetricAttributeKeyProcessName, SapnetweaverProcessAvailabilityMetricAttributeKeyProcessDescription, SapnetweaverProcessAvailabilityMetricAttributeKeyControlState},
					},
					SapnetweaverQueueCount: SapnetweaverQueueCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverQueueCountMetricAttributeKey{SapnetweaverQueueCountMetricAttributeKeyWpType},
					},
					SapnetweaverQueueMaxCount: SapnetweaverQueueMaxCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverQueueMaxCountMetricAttributeKey{SapnetweaverQueueMaxCountMetricAttributeKeyWpType},
					},
					SapnetweaverQueuePeakCount: SapnetweaverQueuePeakCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverQueuePeakCountMetricAttributeKey{SapnetweaverQueuePeakCountMetricAttributeKeyWpType},
					},
					SapnetweaverRequestCount: SapnetweaverRequestCountMetricConfig{
						Enabled: false,
					},
					SapnetweaverRequestTimeoutCount: SapnetweaverRequestTimeoutCountMetricConfig{
						Enabled: false,
					},
					SapnetweaverResponseDuration: SapnetweaverResponseDurationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverResponseDurationMetricAttributeKey{SapnetweaverResponseDurationMetricAttributeKeyResponseType},
					},
					SapnetweaverSessionCount: SapnetweaverSessionCountMetricConfig{
						Enabled: false,
					},
					SapnetweaverSessionsBrowserCount: SapnetweaverSessionsBrowserCountMetricConfig{
						Enabled: false,
					},
					SapnetweaverSessionsEjbCount: SapnetweaverSessionsEjbCountMetricConfig{
						Enabled: false,
					},
					SapnetweaverSessionsHTTPCount: SapnetweaverSessionsHTTPCountMetricConfig{
						Enabled: false,
					},
					SapnetweaverSessionsSecurityCount: SapnetweaverSessionsSecurityCountMetricConfig{
						Enabled: false,
					},
					SapnetweaverSessionsWebCount: SapnetweaverSessionsWebCountMetricConfig{
						Enabled: false,
					},
					SapnetweaverShortDumpsRate: SapnetweaverShortDumpsRateMetricConfig{
						Enabled: false,
					},
					SapnetweaverSpoolRequestErrorCount: SapnetweaverSpoolRequestErrorCountMetricConfig{
						Enabled: false,
					},
					SapnetweaverSystemInstanceAvailability: SapnetweaverSystemInstanceAvailabilityMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverSystemInstanceAvailabilityMetricAttributeKey{SapnetweaverSystemInstanceAvailabilityMetricAttributeKeyHostname, SapnetweaverSystemInstanceAvailabilityMetricAttributeKeyInstanceNumber, SapnetweaverSystemInstanceAvailabilityMetricAttributeKeyFeature, SapnetweaverSystemInstanceAvailabilityMetricAttributeKeyControlState},
					},
					SapnetweaverWorkProcessActiveCount: SapnetweaverWorkProcessActiveCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverWorkProcessActiveCountMetricAttributeKey{SapnetweaverWorkProcessActiveCountMetricAttributeKeyInstance, SapnetweaverWorkProcessActiveCountMetricAttributeKeyWpType, SapnetweaverWorkProcessActiveCountMetricAttributeKeyWpStatus},
					},
					SapnetweaverWorkProcessJobAbortedStatus: SapnetweaverWorkProcessJobAbortedStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SapnetweaverWorkProcessJobAbortedStatusMetricAttributeKey{SapnetweaverWorkProcessJobAbortedStatusMetricAttributeKeyControlState},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					SapnetweaverSID:      ResourceAttributeConfig{Enabled: false},
					SapnetweaverInstance: ResourceAttributeConfig{Enabled: false},
					SapnetweaverNode:     ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(SapnetweaverAbapUpdateStatusMetricConfig{}, SapnetweaverCacheEvictionsMetricConfig{}, SapnetweaverCacheHitsMetricConfig{}, SapnetweaverConnectionErrorCountMetricConfig{}, SapnetweaverCPUSystemUtilizationMetricConfig{}, SapnetweaverCPUUtilizationMetricConfig{}, SapnetweaverDatabaseDialogRequestTimeMetricConfig{}, SapnetweaverHostMemoryVirtualOverheadMetricConfig{}, SapnetweaverHostMemoryVirtualSwapMetricConfig{}, SapnetweaverHostSpoolListUtilizationMetricConfig{}, SapnetweaverLocksDequeueErrorsCountMetricConfig{}, SapnetweaverLocksEnqueueCurrentCountMetricConfig{}, SapnetweaverLocksEnqueueErrorsCountMetricConfig{}, SapnetweaverLocksEnqueueHighCountMetricConfig{}, SapnetweaverLocksEnqueueLockTimeMetricConfig{}, SapnetweaverLocksEnqueueLockWaitTimeMetricConfig{}, SapnetweaverLocksEnqueueMaxCountMetricConfig{}, SapnetweaverMemoryConfiguredMetricConfig{}, SapnetweaverMemoryFreeMetricConfig{}, SapnetweaverMemorySwapSpaceUtilizationMetricConfig{}, SapnetweaverProcessAvailabilityMetricConfig{}, SapnetweaverQueueCountMetricConfig{}, SapnetweaverQueueMaxCountMetricConfig{}, SapnetweaverQueuePeakCountMetricConfig{}, SapnetweaverRequestCountMetricConfig{}, SapnetweaverRequestTimeoutCountMetricConfig{}, SapnetweaverResponseDurationMetricConfig{}, SapnetweaverSessionCountMetricConfig{}, SapnetweaverSessionsBrowserCountMetricConfig{}, SapnetweaverSessionsEjbCountMetricConfig{}, SapnetweaverSessionsHTTPCountMetricConfig{}, SapnetweaverSessionsSecurityCountMetricConfig{}, SapnetweaverSessionsWebCountMetricConfig{}, SapnetweaverShortDumpsRateMetricConfig{}, SapnetweaverSpoolRequestErrorCountMetricConfig{}, SapnetweaverSystemInstanceAvailabilityMetricConfig{}, SapnetweaverWorkProcessActiveCountMetricConfig{}, SapnetweaverWorkProcessJobAbortedStatusMetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}
func TestSapnetweaverAbapUpdateStatusMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SapnetweaverAbapUpdateStatus
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SapnetweaverAbapUpdateStatusMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric sapnetweaver.abap.update.status doesn't have an attribute invalid, valid attributes: [state]")

	cfg = DefaultMetricsConfig().SapnetweaverAbapUpdateStatus
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSapnetweaverProcessAvailabilityMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SapnetweaverProcessAvailability
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SapnetweaverProcessAvailabilityMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric sapnetweaver.process_availability doesn't have an attribute invalid, valid attributes: [process_name, process_description, state]")

	cfg = DefaultMetricsConfig().SapnetweaverProcessAvailability
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSapnetweaverQueueCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SapnetweaverQueueCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SapnetweaverQueueCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric sapnetweaver.queue.count doesn't have an attribute invalid, valid attributes: [wp_type]")

	cfg = DefaultMetricsConfig().SapnetweaverQueueCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSapnetweaverQueueMaxCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SapnetweaverQueueMaxCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SapnetweaverQueueMaxCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric sapnetweaver.queue_max.count doesn't have an attribute invalid, valid attributes: [wp_type]")

	cfg = DefaultMetricsConfig().SapnetweaverQueueMaxCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSapnetweaverQueuePeakCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SapnetweaverQueuePeakCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SapnetweaverQueuePeakCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric sapnetweaver.queue_peak.count doesn't have an attribute invalid, valid attributes: [wp_type]")

	cfg = DefaultMetricsConfig().SapnetweaverQueuePeakCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSapnetweaverResponseDurationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SapnetweaverResponseDuration
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SapnetweaverResponseDurationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric sapnetweaver.response.duration doesn't have an attribute invalid, valid attributes: [response_type]")

	cfg = DefaultMetricsConfig().SapnetweaverResponseDuration
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSapnetweaverSystemInstanceAvailabilityMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SapnetweaverSystemInstanceAvailability
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SapnetweaverSystemInstanceAvailabilityMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric sapnetweaver.system.instance_availability doesn't have an attribute invalid, valid attributes: [hostname, instance_number, feature, state]")

	cfg = DefaultMetricsConfig().SapnetweaverSystemInstanceAvailability
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSapnetweaverWorkProcessActiveCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SapnetweaverWorkProcessActiveCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SapnetweaverWorkProcessActiveCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric sapnetweaver.work_process.active.count doesn't have an attribute invalid, valid attributes: [instance, wp_type, wp_status]")

	cfg = DefaultMetricsConfig().SapnetweaverWorkProcessActiveCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSapnetweaverWorkProcessJobAbortedStatusMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SapnetweaverWorkProcessJobAbortedStatus
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SapnetweaverWorkProcessJobAbortedStatusMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric sapnetweaver.work_process.job.aborted.status doesn't have an attribute invalid, valid attributes: [state]")

	cfg = DefaultMetricsConfig().SapnetweaverWorkProcessJobAbortedStatus
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				SapnetweaverSID:      ResourceAttributeConfig{Enabled: true},
				SapnetweaverInstance: ResourceAttributeConfig{Enabled: true},
				SapnetweaverNode:     ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				SapnetweaverSID:      ResourceAttributeConfig{Enabled: false},
				SapnetweaverInstance: ResourceAttributeConfig{Enabled: false},
				SapnetweaverNode:     ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
