// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	aws "github.com/observiq/bindplane-otel-contrib/receiver/awss3rehydrationreceiver/internal/aws"

	mock "github.com/stretchr/testify/mock"
)

// MockS3Client is an autogenerated mock type for the S3Client type
type MockS3Client struct {
	mock.Mock
}

type MockS3Client_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3Client) EXPECT() *MockS3Client_Expecter {
	return &MockS3Client_Expecter{mock: &_m.Mock}
}

// DeleteObject provides a mock function with given fields: ctx, bucket, key
func (_m *MockS3Client) DeleteObject(ctx context.Context, bucket string, key string) error {
	ret := _m.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, bucket, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockS3Client_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockS3Client_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
func (_e *MockS3Client_Expecter) DeleteObject(ctx interface{}, bucket interface{}, key interface{}) *MockS3Client_DeleteObject_Call {
	return &MockS3Client_DeleteObject_Call{Call: _e.mock.On("DeleteObject", ctx, bucket, key)}
}

func (_c *MockS3Client_DeleteObject_Call) Run(run func(ctx context.Context, bucket string, key string)) *MockS3Client_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockS3Client_DeleteObject_Call) Return(_a0 error) *MockS3Client_DeleteObject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockS3Client_DeleteObject_Call) RunAndReturn(run func(context.Context, string, string) error) *MockS3Client_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadObject provides a mock function with given fields: ctx, bucket, key, buf
func (_m *MockS3Client) DownloadObject(ctx context.Context, bucket string, key string, buf []byte) (int64, error) {
	ret := _m.Called(ctx, bucket, key, buf)

	if len(ret) == 0 {
		panic("no return value specified for DownloadObject")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) (int64, error)); ok {
		return rf(ctx, bucket, key, buf)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) int64); ok {
		r0 = rf(ctx, bucket, key, buf)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []byte) error); ok {
		r1 = rf(ctx, bucket, key, buf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockS3Client_DownloadObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadObject'
type MockS3Client_DownloadObject_Call struct {
	*mock.Call
}

// DownloadObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
//   - buf []byte
func (_e *MockS3Client_Expecter) DownloadObject(ctx interface{}, bucket interface{}, key interface{}, buf interface{}) *MockS3Client_DownloadObject_Call {
	return &MockS3Client_DownloadObject_Call{Call: _e.mock.On("DownloadObject", ctx, bucket, key, buf)}
}

func (_c *MockS3Client_DownloadObject_Call) Run(run func(ctx context.Context, bucket string, key string, buf []byte)) *MockS3Client_DownloadObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *MockS3Client_DownloadObject_Call) Return(_a0 int64, _a1 error) *MockS3Client_DownloadObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockS3Client_DownloadObject_Call) RunAndReturn(run func(context.Context, string, string, []byte) (int64, error)) *MockS3Client_DownloadObject_Call {
	_c.Call.Return(run)
	return _c
}

// StreamObjects provides a mock function with given fields: ctx, bucket, prefix, objectChan, errChan, doneChan
func (_m *MockS3Client) StreamObjects(ctx context.Context, bucket string, prefix string, objectChan chan *aws.ObjectResults, errChan chan error, doneChan chan struct{}) {
	_m.Called(ctx, bucket, prefix, objectChan, errChan, doneChan)
}

// MockS3Client_StreamObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamObjects'
type MockS3Client_StreamObjects_Call struct {
	*mock.Call
}

// StreamObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - prefix string
//   - objectChan chan *aws.ObjectResults
//   - errChan chan error
//   - doneChan chan struct{}
func (_e *MockS3Client_Expecter) StreamObjects(ctx interface{}, bucket interface{}, prefix interface{}, objectChan interface{}, errChan interface{}, doneChan interface{}) *MockS3Client_StreamObjects_Call {
	return &MockS3Client_StreamObjects_Call{Call: _e.mock.On("StreamObjects", ctx, bucket, prefix, objectChan, errChan, doneChan)}
}

func (_c *MockS3Client_StreamObjects_Call) Run(run func(ctx context.Context, bucket string, prefix string, objectChan chan *aws.ObjectResults, errChan chan error, doneChan chan struct{})) *MockS3Client_StreamObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(chan *aws.ObjectResults), args[4].(chan error), args[5].(chan struct{}))
	})
	return _c
}

func (_c *MockS3Client_StreamObjects_Call) Return() *MockS3Client_StreamObjects_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockS3Client_StreamObjects_Call) RunAndReturn(run func(context.Context, string, string, chan *aws.ObjectResults, chan error, chan struct{})) *MockS3Client_StreamObjects_Call {
	_c.Run(run)
	return _c
}

// NewMockS3Client creates a new instance of MockS3Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3Client {
	mock := &MockS3Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
