receivers:
  telemetrygeneratorreceiver:
    payloads_per_second: 1
    generators:
      - type: logs
        resource_attributes:
          source: "test-generator"
        attributes:
          log.type: "security"
        additional_config:
          body: '{"user": "admin", "action": "login", "src_ip": "192.168.1.100", "status": "success"}'
          severity: 9

processors:
  transform:
    log_statements:
      - context: log
        statements:
          - merge_maps(cache, ParseJSON(body.string), "upsert")
          - set(body, cache)

  ocsf_standardization:
    ocsf_version: "1.1.0"
    event_mappings:
      - class_id: 3001
        filter: 'attributes["log.type"] == "security"'
        field_mappings:
          - default: "Bindplane Agent"
            to: "source.name"
          - to: "activity_id"
            default: 2
          - to: "category_uid"
            default: 3
          - to: "severity_id"
            default: 3
          - to: "time"
            default: 1773588497000
          - to: "type_uid"
            default: 300102
          - to: "user.name"
            default: "test"
          - to: "metadata.product.name"
            default: "bindplane"
          - to: "metadata.product.vendor_name"
            default: "observIQ"
          - from: 'body["action"]'
            to: "activity_name"
          - from: 'body["src_ip"]'
            to: "src_endpoint.ip"
          - from: 'body["status"]'
            to: "status"

  groupbyattrs:
    keys:
      - ocsf.class_id

  batch:
    send_batch_size: 100 # flush when 100 events per classID
    timeout: 5s # or every 200ms
    send_batch_max_size: 0 # no hard upper limit

exporters:
  # debug:
  #   verbosity: detailed

  aws_security_lake:
    region: "us-east-2"
    s3_bucket: "aws-security-data-lake-us-east-2-rk917bb7wg9oncy24mrvafihaafpeh"
    account_id: "814871541250"
    ocsf_version: "1.1.0"
    custom_sources:
      - name: "BPAccountChange"
        class_id: 3001

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    logs:
      receivers: [telemetrygeneratorreceiver]
      processors: [transform, ocsf_standardization, groupbyattrs, batch]
      exporters: [aws_security_lake]
