// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/s3event component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("s3event")
	ScopeName = "github.com/observiq/bindplane-otel-contrib/receiver/awss3eventreceiver"
)

const (
	LogsStability = component.StabilityLevelBeta
)
