// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/azureblobpolling component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("azureblobpolling")
	ScopeName = "github.com/observiq/bindplane-otel-contrib/receiver/azureblobpollingreceiver"
)

const (
	MetricsStability = component.StabilityLevelBeta
	LogsStability    = component.StabilityLevelBeta
	TracesStability  = component.StabilityLevelBeta
)
