// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/observiq/bindplane-otel-contrib/processor/bytebatcherprocessor")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/observiq/bindplane-otel-contrib/processor/bytebatcherprocessor")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                         metric.Meter
	mu                            sync.Mutex
	registrations                 []metric.Registration
	ProcessorBatchSendSizeLogs    metric.Int64Gauge
	ProcessorBatchSendSizeMetrics metric.Int64Gauge
	ProcessorBatchSendSizeTraces  metric.Int64Gauge
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ProcessorBatchSendSizeLogs, err = builder.meter.Int64Gauge(
		"otelcol_processor_batch_send_size_logs",
		metric.WithDescription("The size of the last logs batch sent in bytes. [Alpha]"),
		metric.WithUnit("B"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorBatchSendSizeMetrics, err = builder.meter.Int64Gauge(
		"otelcol_processor_batch_send_size_metrics",
		metric.WithDescription("The size of the last metrics batch sent in bytes. [Alpha]"),
		metric.WithUnit("B"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorBatchSendSizeTraces, err = builder.meter.Int64Gauge(
		"otelcol_processor_batch_send_size_traces",
		metric.WithDescription("The size of the last traces batch sent in bytes. [Alpha]"),
		metric.WithUnit("B"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
