// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/asim_standardization component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("asim_standardization")
	ScopeName = "github.com/observiq/bindplane-otel-contrib/processor/asimstandardizationprocessor"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
