name: pr_checks
on:
  pull_request:

jobs:
  # Detect which files changed to skip irrelevant jobs on PRs.
  detect-changes:
    runs-on: namespace-profile-bindplane-default-ubuntu-24-04
    permissions:
      contents: read
      pull-requests: read
    outputs:
      # if this file changed, run all checks. if the makefile changed, run all checks.
      go: ${{ steps.filter.outputs.go == 'true' || steps.filter.outputs.checks == 'true' || steps.filter.outputs.makefile == 'true'  }}
      scripts: ${{ steps.filter.outputs.scripts == 'true' || steps.filter.outputs.checks == 'true' || steps.filter.outputs.makefile == 'true' }}
      misspell: ${{ steps.filter.outputs.misspell == 'true' || steps.filter.outputs.checks == 'true' || steps.filter.outputs.makefile == 'true' }}
      gomod: ${{ steps.filter.outputs.gomod == 'true' || steps.filter.outputs.checks == 'true' || steps.filter.outputs.makefile == 'true' }}
      dependabot: ${{ steps.filter.outputs.dependabot == 'true' || steps.filter.outputs.checks == 'true' || steps.filter.outputs.makefile == 'true' }}
    steps:
      - name: Checkout Sources
        uses: namespacelabs/nscloud-checkout-action@v7
      - name: Detect changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          # These filters are based on picomatch syntax https://github.com/micromatch/picomatch#
          filters: |
            checks:
              - '.github/workflows/checks.yml'
            makefile:
              - 'Makefile'
            go:
              - '**/*.go'
              - '**/go.mod'
              - '**/go.sum'
            scripts:
              - '**/*.sh'
            misspell:
              - '**/*.md'
              - '**/*.yaml'
            gomod:
              - '**/go.mod'
            dependabot:
              - '.github/dependabot.yml'

  setup-tools:
    if: github.actor != 'dependabot[bot]'
    runs-on: namespace-profile-bindplane-default-ubuntu-24-04
    steps:
      - name: Checkout Sources
        uses: namespacelabs/nscloud-checkout-action@v7
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: internal/tools/go.mod
          cache: false # Use Namespace caching instead
      - name: Set up Go cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: go
      - name: Cache Tools
        id: tool-cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: /home/runner/go/bin
      - name: Install Tools
        run: make install-tools

  check-fmt:
    if: github.actor != 'dependabot[bot]' && needs.detect-changes.outputs.go == 'true'
    runs-on: namespace-profile-bindplane-default-ubuntu-24-04
    needs:
      - setup-tools
      - detect-changes
    steps:
      - name: Checkout Sources
        uses: namespacelabs/nscloud-checkout-action@v7
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: internal/tools/go.mod
          cache: false # Use Namespace caching instead
      - name: Set up Go cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: go
      - name: Cache Tools
        id: tool-cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: /home/runner/go/bin
      - name: Install Tools
        run: make install-tools
      - name: Check Formatting
        run: make check-fmt

  check-license:
    if: github.actor != 'dependabot[bot]' && (needs.detect-changes.outputs.go == 'true' || needs.detect-changes.outputs.scripts == 'true')
    runs-on: namespace-profile-bindplane-default-ubuntu-24-04
    needs:
      - setup-tools
      - detect-changes
    steps:
      - name: Checkout Sources
        uses: namespacelabs/nscloud-checkout-action@v7
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: internal/tools/go.mod
          cache: false # Use Namespace caching instead
      - name: Set up Go cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: go
      - name: Cache Tools
        id: tool-cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: /home/runner/go/bin
      - name: Install Tools
        run: make install-tools
      - name: Check License Headers
        run: make check-license

  gosec:
    if: github.actor != 'dependabot[bot]' && needs.detect-changes.outputs.go == 'true'
    runs-on: namespace-profile-bindplane-default-ubuntu-24-04
    needs:
      - setup-tools
      - detect-changes
    steps:
      - name: Checkout Source
        uses: namespacelabs/nscloud-checkout-action@v7
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: internal/tools/go.mod
          cache: false # Use Namespace caching instead
      - name: Set up Go cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: go
      - name: Cache Tools
        id: tool-cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: /home/runner/go/bin
      - name: Install Tools
        run: make install-tools
      - name: Run Gosec Security Scanner
        run: make gosec

  misspell:
    if: github.actor != 'dependabot[bot]' && needs.detect-changes.outputs.misspell == 'true'
    runs-on: namespace-profile-bindplane-default-ubuntu-24-04
    needs:
      - setup-tools
      - detect-changes
    steps:
      - name: Checkout Sources
        uses: namespacelabs/nscloud-checkout-action@v7
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: internal/tools/go.mod
          cache: false # Use Namespace caching instead
      - name: Set up Go cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: go
      - name: Cache Tools
        id: tool-cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: /home/runner/go/bin
      - name: Install Tools
        run: make install-tools
      - name: Check for Misspelled Words in Doc Files
        run: make misspell

  lint:
    if: github.actor != 'dependabot[bot]' && needs.detect-changes.outputs.go == 'true'
    runs-on: namespace-profile-bindplane-default-ubuntu-24-04
    needs:
      - setup-tools
      - detect-changes
    steps:
      - name: Checkout Sources
        uses: namespacelabs/nscloud-checkout-action@v7
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: internal/tools/go.mod
          cache: false # Use Namespace caching instead
      - name: Set up Go cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: go
      - name: Cache Tools
        id: tool-cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: /home/runner/go/bin
      - name: Install Tools
        run: make install-tools
      - name: Run Revive Linter
        run: make lint

  # Below checks don't need to run `make install-tools`
  check-mod-paths:
    if: github.actor != 'dependabot[bot]' && needs.detect-changes.outputs.gomod == 'true'
    runs-on: namespace-profile-bindplane-default-ubuntu-24-04
    needs:
      - detect-changes
    steps:
      - name: Checkout Sources
        uses: namespacelabs/nscloud-checkout-action@v7
      - name: Check Module Paths
        run: make check-mod-paths

  check-dependabot:
    if: github.actor != 'dependabot[bot]' && (needs.detect-changes.outputs.dependabot == 'true' || needs.detect-changes.outputs.gomod == 'true')
    runs-on: namespace-profile-bindplane-default-ubuntu-24-04
    needs:
      - detect-changes
    steps:
      - name: Checkout Sources
        uses: namespacelabs/nscloud-checkout-action@v7
      - name: Check Dependabot
        run: make check-dependabot
