// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					M365OnedriveFilesActiveCount: M365OnedriveFilesActiveCountMetricConfig{
						Enabled: true,
					},
					M365OnedriveFilesCount: M365OnedriveFilesCountMetricConfig{
						Enabled: true,
					},
					M365OnedriveUserActivityCount: M365OnedriveUserActivityCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []M365OnedriveUserActivityCountMetricAttributeKey{M365OnedriveUserActivityCountMetricAttributeKeyOnedriveActivity},
					},
					M365OutlookAppUserCount: M365OutlookAppUserCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []M365OutlookAppUserCountMetricAttributeKey{M365OutlookAppUserCountMetricAttributeKeyOutlookApps},
					},
					M365OutlookEmailActivityCount: M365OutlookEmailActivityCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []M365OutlookEmailActivityCountMetricAttributeKey{M365OutlookEmailActivityCountMetricAttributeKeyOutlookActivity},
					},
					M365OutlookMailboxesActiveCount: M365OutlookMailboxesActiveCountMetricConfig{
						Enabled: true,
					},
					M365OutlookQuotaStatusCount: M365OutlookQuotaStatusCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []M365OutlookQuotaStatusCountMetricAttributeKey{M365OutlookQuotaStatusCountMetricAttributeKeyOutlookQuotas},
					},
					M365OutlookStorageUsed: M365OutlookStorageUsedMetricConfig{
						Enabled: true,
					},
					M365SharepointFilesActiveCount: M365SharepointFilesActiveCountMetricConfig{
						Enabled: true,
					},
					M365SharepointFilesCount: M365SharepointFilesCountMetricConfig{
						Enabled: true,
					},
					M365SharepointPagesUniqueCount: M365SharepointPagesUniqueCountMetricConfig{
						Enabled: true,
					},
					M365SharepointPagesViewedCount: M365SharepointPagesViewedCountMetricConfig{
						Enabled: true,
					},
					M365SharepointSiteStorageUsed: M365SharepointSiteStorageUsedMetricConfig{
						Enabled: true,
					},
					M365SharepointSitesActiveCount: M365SharepointSitesActiveCountMetricConfig{
						Enabled: true,
					},
					M365TeamsCallsCount: M365TeamsCallsCountMetricConfig{
						Enabled: true,
					},
					M365TeamsDeviceUsageUsers: M365TeamsDeviceUsageUsersMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []M365TeamsDeviceUsageUsersMetricAttributeKey{M365TeamsDeviceUsageUsersMetricAttributeKeyTeamsDevices},
					},
					M365TeamsMeetingsCount: M365TeamsMeetingsCountMetricConfig{
						Enabled: true,
					},
					M365TeamsMessagesPrivateCount: M365TeamsMessagesPrivateCountMetricConfig{
						Enabled: true,
					},
					M365TeamsMessagesTeamCount: M365TeamsMessagesTeamCountMetricConfig{
						Enabled: true,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					M365TenantID: ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					M365OnedriveFilesActiveCount: M365OnedriveFilesActiveCountMetricConfig{
						Enabled: false,
					},
					M365OnedriveFilesCount: M365OnedriveFilesCountMetricConfig{
						Enabled: false,
					},
					M365OnedriveUserActivityCount: M365OnedriveUserActivityCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []M365OnedriveUserActivityCountMetricAttributeKey{M365OnedriveUserActivityCountMetricAttributeKeyOnedriveActivity},
					},
					M365OutlookAppUserCount: M365OutlookAppUserCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []M365OutlookAppUserCountMetricAttributeKey{M365OutlookAppUserCountMetricAttributeKeyOutlookApps},
					},
					M365OutlookEmailActivityCount: M365OutlookEmailActivityCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []M365OutlookEmailActivityCountMetricAttributeKey{M365OutlookEmailActivityCountMetricAttributeKeyOutlookActivity},
					},
					M365OutlookMailboxesActiveCount: M365OutlookMailboxesActiveCountMetricConfig{
						Enabled: false,
					},
					M365OutlookQuotaStatusCount: M365OutlookQuotaStatusCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []M365OutlookQuotaStatusCountMetricAttributeKey{M365OutlookQuotaStatusCountMetricAttributeKeyOutlookQuotas},
					},
					M365OutlookStorageUsed: M365OutlookStorageUsedMetricConfig{
						Enabled: false,
					},
					M365SharepointFilesActiveCount: M365SharepointFilesActiveCountMetricConfig{
						Enabled: false,
					},
					M365SharepointFilesCount: M365SharepointFilesCountMetricConfig{
						Enabled: false,
					},
					M365SharepointPagesUniqueCount: M365SharepointPagesUniqueCountMetricConfig{
						Enabled: false,
					},
					M365SharepointPagesViewedCount: M365SharepointPagesViewedCountMetricConfig{
						Enabled: false,
					},
					M365SharepointSiteStorageUsed: M365SharepointSiteStorageUsedMetricConfig{
						Enabled: false,
					},
					M365SharepointSitesActiveCount: M365SharepointSitesActiveCountMetricConfig{
						Enabled: false,
					},
					M365TeamsCallsCount: M365TeamsCallsCountMetricConfig{
						Enabled: false,
					},
					M365TeamsDeviceUsageUsers: M365TeamsDeviceUsageUsersMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []M365TeamsDeviceUsageUsersMetricAttributeKey{M365TeamsDeviceUsageUsersMetricAttributeKeyTeamsDevices},
					},
					M365TeamsMeetingsCount: M365TeamsMeetingsCountMetricConfig{
						Enabled: false,
					},
					M365TeamsMessagesPrivateCount: M365TeamsMessagesPrivateCountMetricConfig{
						Enabled: false,
					},
					M365TeamsMessagesTeamCount: M365TeamsMessagesTeamCountMetricConfig{
						Enabled: false,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					M365TenantID: ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(M365OnedriveFilesActiveCountMetricConfig{}, M365OnedriveFilesCountMetricConfig{}, M365OnedriveUserActivityCountMetricConfig{}, M365OutlookAppUserCountMetricConfig{}, M365OutlookEmailActivityCountMetricConfig{}, M365OutlookMailboxesActiveCountMetricConfig{}, M365OutlookQuotaStatusCountMetricConfig{}, M365OutlookStorageUsedMetricConfig{}, M365SharepointFilesActiveCountMetricConfig{}, M365SharepointFilesCountMetricConfig{}, M365SharepointPagesUniqueCountMetricConfig{}, M365SharepointPagesViewedCountMetricConfig{}, M365SharepointSiteStorageUsedMetricConfig{}, M365SharepointSitesActiveCountMetricConfig{}, M365TeamsCallsCountMetricConfig{}, M365TeamsDeviceUsageUsersMetricConfig{}, M365TeamsMeetingsCountMetricConfig{}, M365TeamsMessagesPrivateCountMetricConfig{}, M365TeamsMessagesTeamCountMetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func TestM365OnedriveUserActivityCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().M365OnedriveUserActivityCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []M365OnedriveUserActivityCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric m365.onedrive.user_activity.count doesn't have an attribute invalid, valid attributes: [activity]")

	cfg = DefaultMetricsConfig().M365OnedriveUserActivityCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestM365OutlookAppUserCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().M365OutlookAppUserCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []M365OutlookAppUserCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric m365.outlook.app.user.count doesn't have an attribute invalid, valid attributes: [app]")

	cfg = DefaultMetricsConfig().M365OutlookAppUserCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestM365OutlookEmailActivityCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().M365OutlookEmailActivityCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []M365OutlookEmailActivityCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric m365.outlook.email_activity.count doesn't have an attribute invalid, valid attributes: [activity]")

	cfg = DefaultMetricsConfig().M365OutlookEmailActivityCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestM365OutlookQuotaStatusCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().M365OutlookQuotaStatusCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []M365OutlookQuotaStatusCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric m365.outlook.quota_status.count doesn't have an attribute invalid, valid attributes: [state]")

	cfg = DefaultMetricsConfig().M365OutlookQuotaStatusCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestM365TeamsDeviceUsageUsersMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().M365TeamsDeviceUsageUsers
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []M365TeamsDeviceUsageUsersMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric m365.teams.device_usage.users doesn't have an attribute invalid, valid attributes: [device]")

	cfg = DefaultMetricsConfig().M365TeamsDeviceUsageUsers
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				M365TenantID: ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				M365TenantID: ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
